In [ ]:
1. Индексация массивов NumPy:

Напишите программу, которая:

- Запрашивает у пользователя ввод одномерного массива, элементы которого вводятся в виде чисел, разделенных пробелами.

- Преобразует введенную строку в массив NumPy.

- Запрашивает у пользователя индекс элемента, который необходимо извлечь из массива.

- Выводит значение элемента по запрошенному индексу.

- Запрашивает у пользователя ввод диапазона индексов в формате `начало:конец`, чтобы извлечь срез массива.

- Выводит срез массива.


In [63]:
import numpy as np

nums = list(map(int, input('Enter numbers with spaces').split()))
arr = np.array(nums)
print(arr)
element = int(input('Enter element number for extracting:'))
print(arr[element])
slice_1, slice_2 = map(int, input('Enter the first index range for slicing: ').split(':'))
print(f'Срез массива: {arr[slice_1:slice_2]}')


Enter numbers with spaces 1 2 3 4 5 6 7 8 9


[1 2 3 4 5 6 7 8 9]


Enter element number for extracting: 2


3


Enter the first index range for slicing:  4:7


Срез массива: [5 6 7]


In [ ]:
2. Операции с матрицами в NumPy:

Напишите программу, которая:

- Запрашивает у пользователя размеры матрицы MxN.

- Генерирует две матрицы указанных размеров, заполненные случайными числами от 0 до 9.

- Выводит обе сгенерированные матрицы на экран.q

- Выполняет и выводит результат одной из следующих операций (на выбор пользователя): сложение матриц, умножение матриц, транспонирование одной из матриц.

- Если выбрано умножение, убедитесь, что размеры матриц соответствуют правилам матричного умножения.

In [ ]:
import random as rd
import numpy as np


size_input = input('Enter matrix size in format MxN: ').lower().replace(' ', '')
try:
    M, N = map(int, size_input.split('x'))
except ValueError:
    print("Invalid input format. Please enter size like '3x4'.")
    exit()

mat_1 = np.random.randint(0, 10, (M, N))
mat_2 = np.random.randint(0, 10, (M, N))

print("\nMatrix 1:")
print(mat_1)

print("\nMatrix 2:")
print(mat_2)

while True:
    operation = input(
        "\nSelect operation:\n"
        " - addition\n"
        " - multiplication\n"
        " - matrix multiplication\n"
        " - transposition\n"
        "Enter 'q' to quit.\nYour choice: ").lower()

    if operation == 'addition':
        print("\nMatrix Addition Result:")
        print(mat_1 + mat_2)

    elif operation == 'multiplication':
        print("\nElement-wise Multiplication Result:")
        print(mat_1 * mat_2)

    elif operation == 'matrix multiplication':

        if mat_1.shape[1] == mat_2.shape[0]:
            result = mat_1 @ mat_2
            print("\nMatrix Multiplication Result:")
            print(result)
        else:
            print(f"\nMatrix multiplication not possible: "
                  f"{mat_1.shape[0]}x{mat_1.shape[1]} @ {mat_2.shape[0]}x{mat_2.shape[1]} — sizes do not match.")

    elif operation == 'transposition':
        T_mat = input("Which matrix to transpose (1 or 2)? ")
        if T_mat == '1':
            print("\nTransposed Matrix 1:")
            print(mat_1.T)
        elif T_mat == '2':
            print("\nTransposed Matrix 2:")
            print(mat_2.T)
        else:
            print("Invalid matrix number. Enter 1 or 2.")

    elif operation == 'q':
        print("Exit")
        break

    else:
        print("Invalid operation. Choose from: addition, multiplication, matrix multiplication, transposition.")

Enter matrix size in format MxN:  3x4



Matrix 1:
[[4 2 6 9]
 [4 2 2 9]
 [8 5 9 5]]

Matrix 2:
[[5 2 8 9]
 [0 8 0 1]
 [3 1 9 8]]



Select operation:
 - addition
 - multiplication
 - matrix multiplication
 - transposition
Enter 'q' to quit.
Your choice:  addition



Matrix Addition Result:
[[ 9  4 14 18]
 [ 4 10  2 10]
 [11  6 18 13]]



Select operation:
 - addition
 - multiplication
 - matrix multiplication
 - transposition
Enter 'q' to quit.
Your choice:  multiplication



Element-wise Multiplication Result:
[[20  4 48 81]
 [ 0 16  0  9]
 [24  5 81 40]]



Select operation:
 - addition
 - multiplication
 - matrix multiplication
 - transposition
Enter 'q' to quit.
Your choice:  matrix multiplication



Matrix multiplication not possible: 3x4 @ 3x4 — sizes do not match.



Select operation:
 - addition
 - multiplication
 - matrix multiplication
 - transposition
Enter 'q' to quit.
Your choice:  transposition
Which matrix to transpose (1 or 2)?  q


Invalid matrix number. Enter 1 or 2.
