In [ ]:
УРОК 42. ТИП ДАННЫХ PANDAS.
DATAFRAME

In [58]:
import pandas as pd
import numpy as np

In [3]:
d = {'one': pd.Series(range(6), index=list('aaaefg'))}
df = pd.DataFrame(d)
df


one
a    0
a    1
a    2
e    3
f    4
g    5

In [4]:
display(pd.Series(range(6), index=list('aaaefg')))
d = {'one': pd.Series(range(6), index=list('aaaefg'))}
df = pd.DataFrame(d)
df

a    0
a    1
a    2
e    3
f    4
g    5
dtype: int64

51
a   0
a   1
a   2
e   3
f   4
g   5

In [5]:
d = {'one': pd.Series(range(6), index=list('aaaefg'))}
df = pd.DataFrame(d)
print(df)

   51
a   0
a   1
a   2
e   3
f   4
g   5


In [6]:
df.reset_index()

index  51
0     a   0
1     a   1
2     a   2
3     e   3
4     f   4
5     g   5

In [ ]:
df.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill=''

In [ ]:
Параметры:
level (int, str, tuple, or list, default None): Уровень индекса(ов), который нужно сбросить. Если None, то сбрасываются все уровни.
drop (bool, default False): Если True, то сбрасываемые уровни индекса будут удалены, а не добавлены в качестве столбцов.
inplace (bool, default False): Если True, операция будет выполнена на месте, и DataFrame будет изменен. Если False, будет возвращена новая копия DataFrame.
col_level (int or str, default 0): Уровень столбцов, на котором будут вставлены новые столбцы.
col_fill (object, default ''): Если вставлять новые уровни столбцов, то значение, которое будет использоваться для заполнения отсутствующих уровней столбцов.

In [7]:
d = {'one': pd.Series(range(6), index=list('abdefg')),
'two': pd.Series(range(7), index=list('abcdefg')),
'three': pd.Series(np.random.normal(size=7), index=list('abcdefg'))}
df = pd.DataFrame(d)
df

one  two     three
a  0.0    0  0.593303
b  1.0    1 -0.534529
c  NaN    2 -0.709887
d  2.0    3  2.447601
e  3.0    4 -0.373698
f  4.0    5  1.144999
g  5.0    6 -1.194849

In [8]:
df['one']

a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
Name: one, dtype: float64

In [9]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [11]:
df2 = pd.DataFrame({ 'A': 1., 'B': pd.Timestamp('20130102'),
'C': pd.Series(1, index=list(range(4)), dtype='float32'),
'D': np.array([3] * 4, dtype='int32'),
'E': pd.Categorical(["test", "train", "test", "train"]), # one - hot encoding
'F': 'foo' })
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [12]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [13]:
df.head() # в аргументе можем указать сколько первых строк хотим вывести

one  two     three
a  0.0    0  0.593303
b  1.0    1 -0.534529
c  NaN    2 -0.709887
d  2.0    3  2.447601
e  3.0    4 -0.373698

In [14]:
df.tail(3) # (а здесь последних). по умолчанию – 5

one  two     three
e  3.0    4 -0.373698
f  4.0    5  1.144999
g  5.0    6 -1.194849

In [15]:
df.index # индексы

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [16]:
df.columns # названия колонок


Index(['one', 'two', 'three'], dtype='object')

In [17]:
df.values # получение обычной матрицы данных

array([[ 0.        ,  0.        ,  0.59330311],
       [ 1.        ,  1.        , -0.5345294 ],
       [        nan,  2.        , -0.70988704],
       [ 2.        ,  3.        ,  2.44760127],
       [ 3.        ,  4.        , -0.37369773],
       [ 4.        ,  5.        ,  1.14499934],
       [ 5.        ,  6.        , -1.19484857]])

In [18]:
df[['one', 'two']] # [[ -- список колонок

one  two
a  0.0    0
b  1.0    1
c  NaN    2
d  2.0    3
e  3.0    4
f  4.0    5
g  5.0    6

In [19]:
df.describe()

one       two     three
count  6.000000  7.000000  7.000000
mean   2.500000  3.000000  0.196134
std    1.870829  2.160247  1.274198
min    0.000000  0.000000 -1.194849
25%    1.250000  1.500000 -0.622208
50%    2.500000  3.000000 -0.373698
75%    3.750000  4.500000  0.869151
max    5.000000  6.000000  2.447601

In [20]:
df.describe()['one']

count    6.000000
mean     2.500000
std      1.870829
min      0.000000
25%      1.250000
50%      2.500000
75%      3.750000
max      5.000000
Name: one, dtype: float64

In [21]:
df.T

a         b         c         d         e         f         g
one    0.000000  1.000000       NaN  2.000000  3.000000  4.000000  5.000000
two    0.000000  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000
three  0.593303 -0.534529 -0.709887  2.447601 -0.373698  1.144999 -1.194849

In [22]:
df.describe().T

count      mean       std       min       25%       50%       75%  \
one      6.0  2.500000  1.870829  0.000000  1.250000  2.500000  3.750000   
two      7.0  3.000000  2.160247  0.000000  1.500000  3.000000  4.500000   
three    7.0  0.196134  1.274198 -1.194849 -0.622208 -0.373698  0.869151   

            max  
one    5.000000  
two    6.000000  
three  2.447601

In [23]:
df.sort_values(by='three', ascending=False)

one  two     three
d  2.0    3  2.447601
f  4.0    5  1.144999
a  0.0    0  0.593303
e  3.0    4 -0.373698
b  1.0    1 -0.534529
c  NaN    2 -0.709887
g  5.0    6 -1.194849

In [26]:
for i in df.columns: # Можно проитерироваться по столбцам:
    print(i, df[i]) # выводит Series

one a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
Name: one, dtype: float64
two a    0
b    1
c    2
d    3
e    4
f    5
g    6
Name: two, dtype: int64
three a    0.593303
b   -0.534529
c   -0.709887
d    2.447601
e   -0.373698
f    1.144999
g   -1.194849
Name: three, dtype: float64


In [29]:
for i, j in df.iterrows(): #Или по строкам. И то, и то неэффективно и следует по возможности избегать прямой
#итерации, заменяя её операциями над датафреймами, о которых мы поговорим позже.
    print(i)
    print(j)
    print()

a
one      0.000000
two      0.000000
three    0.593303
Name: a, dtype: float64

b
one      1.000000
two      1.000000
three   -0.534529
Name: b, dtype: float64

c
one           NaN
two      2.000000
three   -0.709887
Name: c, dtype: float64

d
one      2.000000
two      3.000000
three    2.447601
Name: d, dtype: float64

e
one      3.000000
two      4.000000
three   -0.373698
Name: e, dtype: float64

f
one      4.000000
two      5.000000
three    1.144999
Name: f, dtype: float64

g
one      5.000000
two      6.000000
three   -1.194849
Name: g, dtype: float64



In [30]:
pd.DataFrame(
    np.random.normal(size=(100, 3)),
    columns=['x', 'y', 'z']
).sort_values(by=['x', 'y', 'z'])

x         y         z
51 -2.869622  0.630927 -2.624388
38 -2.699958 -0.564255 -0.778552
68 -2.450974 -1.081844 -0.047374
66 -2.396549 -0.146219  0.962346
49 -1.983342  1.696058 -0.098981
..       ...       ...       ...
28  1.823845  0.676696  1.081057
11  1.954900  1.930907  0.127910
73  2.010945 -1.078490  0.604742
99  2.080566 -1.766669 -1.450249
32  2.119413  0.075203 -0.278955

[100 rows x 3 columns]

In [34]:
pd.DataFrame(
    np.random.normal(size=(10, 3)).astype(int),
    columns=['x', 'y', 'z']
).sort_values(by=['x', 'y', 'z'])

x  y  z
7 -1 -1 -1
4 -1  0  0
0  0  0  0
3  0  0  0
6  0  0  0
8  0  0  0
9  0  0  0
1  0  1  1
2  1  0  0
5  1  0  0

In [35]:
df['one'] # Если в качестве индекса указать имя столбца, получится одномерный набор данных типа Series.

a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
Name: one, dtype: float64

In [36]:
df.one # К столбцу можно обращаться как к полю объекта, если имя столбца позволяет это сделать (= является строкой)

a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
Name: one, dtype: float64

In [37]:
df['one'].index # Индексы полученного одномерного набора данных.

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [38]:
df['one'].name # Можно получить имя данного столбца

'one'

In [39]:
df['one']['d'] # Получение элемента массива. Сначала надо указать столбец, потом строку

np.float64(2.0)

In [40]:
df['c']['one'] # А наоборот нельзя!

KeyError: 'c'

In [41]:
df['b':'d'] # правая граница включена!

one  two     three
b  1.0    1 -0.534529
c  NaN    2 -0.709887
d  2.0    3  2.447601

In [42]:
df[1:3] # но диапазон целых чисел даёт диапазон строк с такими номерами, не включая правую границу (как обычно при индексировании списков).

one  two     three
b  1.0    1 -0.534529
c  NaN    2 -0.709887

In [43]:
df[1] # при этом обратиться к индексу по номеру нельзя, а вот срез взять можно!

KeyError: 1

In [45]:
df[['one', 'three']]

one     three
a  0.0  0.593303
b  1.0 -0.534529
c  NaN -0.709887
d  2.0  2.447601
e  3.0 -0.373698
f  4.0  1.144999
g  5.0 -1.194849

In [46]:
display(df['one'])

a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
Name: one, dtype: float64

In [47]:
display(df[['one']]) 

one
a  0.0
b  1.0
c  NaN
d  2.0
e  3.0
f  4.0
g  5.0

In [ ]:
loc - смотрит на названия столбцов. Берет сначала строки, потом столбцы

In [ ]:
iloc - смотрит на номер строки (индекс строки или столбца по номеру начиная с нуля)

In [48]:
df.loc['b'] # .__index__

one      1.000000
two      1.000000
three   -0.534529
Name: b, dtype: float64

In [49]:
df.loc['b', 'one'] # сначала строки, потом колонки

np.float64(1.0)

In [50]:
df['one']['b'] # эта строка выведет то же что и предыдущая

np.float64(1.0)

In [51]:
df.loc['a':'b', 'one'] # можно использовать срезы по-всякому

a    0.0
b    1.0
Name: one, dtype: float64

In [52]:
df.loc['a':'b', :]

one  two     three
a  0.0    0  0.593303
b  1.0    1 -0.534529

In [ ]:
df.loc[:, 'one'] # двоеточие, напомним, означает, что берем все значения по соответсвующей размерности

In [53]:
df.iloc[2] # атрибут iloc подобен loc: первый индекс — номер строки, второй — номер столбца. Это целые числа, конец диапазона не включается как обычно в питоне

one           NaN
two      2.000000
three   -0.709887
Name: c, dtype: float64

In [54]:
df.iloc[1:3]

one  two     three
b  1.0    1 -0.534529
c  NaN    2 -0.709887

In [55]:
df.iloc[1:3, 0:2] # и тут срезы абсолютно валидны

one  two
b  1.0    1
c  NaN    2

In [56]:
df[df.three > 0]

one  two     three
a  0.0    0  0.593303
d  2.0    3  2.447601
f  4.0    5  1.144999

In [57]:
df[df.notna()]

one  two     three
a  0.0    0  0.593303
b  1.0    1 -0.534529
c  NaN    2 -0.709887
d  2.0    3  2.447601
e  3.0    4 -0.373698
f  4.0    5  1.144999
g  5.0    6 -1.194849

In [ ]:
Сгенерируйте случайную целочисленную матрицу 𝑛×𝑚 , где 𝑛20,𝑚10 . Создайте из
неё датафрейм, пронумеровав столбцы случайной перестановкой чисел из 1,…,𝑚} .
Выберите столбцы с чётными номерами и строки, в которых чётных элементов
больше, чем нечетных.

In [72]:
np.random.seed(42)

n = 20
m = 10

mat = np.random.randint(1, 101, size = (n, m))
print(mat)
heads = np.arange(1, m + 1)
np.random.shuffle(heads)
print(heads)

df = pd.DataFrame(mat, columns = heads)
df

heads_mask = (heads % 2 == 0)
print(heads_mask)

rows_mask = np.sum(mat % 2, axis=1) < m / 2 # 10/2
print(rows_mask)

df.loc[rows_mask, heads_mask]

[[ 52  93  15  72  61  21  83  87  75  75]
 [ 88 100  24   3  22  53   2  88  30  38]
 [  2  64  60  21  33  76  58  22  89  49]
 [ 91  59  42  92  60  80  15  62  62  47]
 [ 62  51  55  64   3  51   7  21  73  39]
 [ 18   4  89  60  14   9  90  53   2  84]
 [ 92  60  71  44   8  47  35  78  81  36]
 [ 50   4   2   6  54   4  54  93  63  18]
 [ 90  44  34  74  62 100  14  95  48  15]
 [ 72  78  87  62  40  85  80  82  53  24]
 [ 26  89  60  41  29  15  45  65  89  71]
 [  9  88   1   8  88  63  11  81   8  35]
 [ 35  33   5  41  28   7  73  72  12  34]
 [ 33  48  23  62  88  37  99  44  86  91]
 [ 35  65  99  47  78   3   1   5  90  14]
 [ 27   9  79  15  90  42  77  51  63  96]
 [ 52  96   4  94  23  15  43  29  36  13]
 [ 32  71  59  86  28  66  42  45  62  57]
 [  6  28  28  44  84  30  62  75  92  89]
 [ 62  97   1  27  62  77   3  70  72  27]]
[ 6  8  7 10  4  2  3  1  5  9]
[ True  True False  True  True  True False False False False]
[False  True  True  True False  True  True  T

6    8   10  4    2 
1   88  100   3  22   53
2    2   64  21  33   76
3   91   59  92  60   80
5   18    4  60  14    9
6   92   60  44   8   47
7   50    4   6  54    4
8   90   44  74  62  100
9   72   78  62  40   85
17  32   71  86  28   66
18   6   28  44  84   30