In [ ]:
1. Напишите программу, которая:
a. Запрашивает у пользователя ввод двух списков – в первом 5
элементов, во втором 4. Списки вводятся в виде чисел, разделенных
пробелами.
b. Объединяет введенные списки в один новый список из 9 элементов.
c. Преобразует полученный список в массив NumPy.
d. Трансформирует одномерный массив в матрицу размера 3х3.
Обозначим эту матрицу Х.
e. Выводит полученную матрицу.


In [15]:
import numpy as np

lst_1 = list(map(int, input('Enter 5 elements with spaces').split()))
lst_2 = list(map(int, input('Enter 4 elements with spaces').split()))
lst_total = lst_1 + lst_2
print(lst_total)
X = np.array(lst_total).reshape(3,3)
print(X)

Enter 5 elements with spaces 1 2 3 4 5
Enter 4 elements with spaces 6 7 8 9


[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
2. Продолжение предыдущей задачи. Далее она:
a. В каждой строке и в каждом столбце находит среднее, максимум,
минимум, сумму, произведение.
b. Для всей матрицы находит среднее, максимум, минимум, сумму,
произведение и след.
c. Выводит транспонированную матрицу для матрицы Х.


In [5]:
print(np.mean(X, axis=1)) # описание, что перебирать (столбцы), X-ось
print(np.mean(X, axis=0)) # строки по вертикали (axis = 0, это как Y-ось)
print(np.sum(X, axis=1))
print(np.sum(X, axis=0))

[2. 5. 8.]
[4. 5. 6.]
[ 6 15 24]
[12 15 18]


In [ ]:
# вариант 2

print(f"X:\n{X}")
print()
print("Operations by ROWs")
print(f"Mean by rows X = {np.mean(X, axis=1)}")
print(f"Max  by rows X = {np.max(X,axis=1)}")
print(f"Min  by rows X = {np.min(X,axis=1)}")
print(f"Sum  by rows X = {np.min(X,axis=1)}")
print()
print("operations by COLUMNs")
print(f"Mean by columns X = {np.mean(X, axis=0)}")
print(f"Max  by columns X = {np.max(X,axis=0)}")
print(f"Min  by columns X = {np.min(X,axis=0)}")
print(f"Sum  by columns X = {np.sum(X,axis=0)}")
print()
print("Operations with Full Table") 
print(f"Mean  X = {np.mean(X)}")
print(f"Max   X = {np.max(X)}")
print(f"Min   X = {np.min(X)}")
print(f"Prod  X = {np.prod(X)}")
print(f"Trace X = {np.trace(X)}")
print()
print(f"X.T :\n {X.T}")

In [6]:
lst_trace = np.trace(X)
print(lst_trace)

15


In [7]:
lst_T = X.T
print(lst_T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
3. Продолжение предыдущей задачи. Далее она:
a. Генерирует массив из трех случайных элементов. Этот вектор-строку
обозначим А.
b. Трансформирует вектор-строку в вектор-столбец. Его обозначим B.
c. Матрицу Х умножает на вектор-строку А.
d. Матрицу Х умножает на вектор-столбец B.
e. Выполняет матричное умножение матриц из предыдущих пунктов.


In [8]:
print("Матрица X:")
print(X)

# vector_A = np.array([rd.uniform(0, 10) for i in range (3)])
vector_A = np.random.randint(1, 11, size=3)
print("\nВектор-строка A:")
print(vector_A)

vector_B = vector_A[:, np.newaxis]
print("\nВектор-столбец B:")
print(vector_B)

result_c = X * vector_A
print("\nУмножение матрицы X на вектор-строку A:")
print(result_c)

result_d = X * vector_B
print("\nУмножение матрицы X на вектор-столбец B:")
print(result_d)

result_e = result_c @ result_d
print("\nМатричное умножение результатов из пунктов c и d:")
print(result_e)

Матрица X:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Вектор-строка A:
[7 8 7]

Вектор-столбец B:
[[7]
 [8]
 [7]]

Умножение матрицы X на вектор-строку A:
[[ 7 16 21]
 [28 40 42]
 [49 64 63]]

Умножение матрицы X на вектор-столбец B:
[[ 7 14 21]
 [32 40 48]
 [49 56 63]]

Матричное умножение результатов из пунктов c и d:
[[1590 1914 2238]
 [3534 4344 5154]
 [5478 6774 8070]]


In [ ]:
4. Продолжение предыдущей задачи. Далее она:
a. Запрашивает у пользователя число i от 0 до 2.
b. Выводит строку i из матрицы Х.
c. Выводит столбец i из матрицы Х.

In [14]:
print(X)
num = int(input('Enter number from 0 to 2')) #check num [0-2]
print(X[num])
print(X[:, num])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Enter number from 0 to 2 0


[1 2 3]
[1 4 7]


In [ ]:
5. Создайте матрицу 5х5 из чисел от 1 до 25. Из этой матрицы извлеките две
подматрицы: С размера 2х3 из левого верхнего угла исходной матрицы, и В
размера 3х2 из правого нижнего угла исходной матрицы. Найдите матричное
произведение С на B и B на С.

In [28]:
mat = np.arange(1, 26).reshape(5,5)
print(mat)
C = mat[0:2, 0:3]
print(C)
B = mat[2:5, 3:5]
print(B)
print(C @ B)
print(B @ C)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[1 2 3]
 [6 7 8]]
[[14 15]
 [19 20]
 [24 25]]
[[124 130]
 [409 430]]
[[104 133 162]
 [139 178 217]
 [174 223 272]]


In [29]:
print(B * C)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [30]:
print(B * C.T)

[[ 14  90]
 [ 38 140]
 [ 72 200]]


In [ ]:
6. Запросите у пользователя ввод трех чисел – x, y, z. Создайте трехмерный
массив размера x*y*z и заполните его числами от 10 до 20 с подходящим
шагом. Выведите его. Запросите у пользователя координаты элемента этого
тензора и его новое значение. Замените выбранный элемент на новое
значение.
Вычислите среднее, максимум, минимум, сумму, произведение по каждой
оси.

In [ ]:
x = int(input("Введите размер x: "))
y = int(input("Введите размер y: "))
z = int(input("Введите размер z: "))
arr = np.linspace(10, 20, x * y * z).reshape(x, y, z)
print(arr)

In [ ]:
# Запросите у пользователя координаты элемента этого тензора и его новое значение. 
# Замените выбранный элемент на новое значение
i = int(input("Введите координату по оси x: "))
j = int(input("Введите координату по оси y: "))
k = int(input("Введите координату по оси z: "))
new_value = float(input("Введите новое значение: "))

arr[i, j, k] = new_value
# Запросите у пользователя координаты элемента этого тензора и его новое значение. 
# Замените выбранный элемент на новое значение
i = int(input("Введите координату по оси x: "))
j = int(input("Введите координату по оси y: "))
k = int(input("Введите координату по оси z: "))
new_value = float(input("Введите новое значение: "))

arr[i, j, k] = new_value
print("Обновленный массив:\n", arr)

In [ ]:
# Вычислите среднее, максимум, минимум, сумму, произведение по каждой оси
print("\nОсь x:")
print("Среднее:", np.mean(arr, axis=0))
print("Максимум:", np.max(arr, axis=0))
print("Минимум:", np.min(arr, axis=0))
print("Сумма:", np.sum(arr, axis=0))
print("Произведение:", np.prod(arr, axis=0))

print("\nОсь y:")
print("Среднее:", np.mean(arr, axis=1))
print("Максимум:", np.max(arr, axis=1))
print("Минимум:", np.min(arr, axis=1))
print("Сумма:", np.sum(arr, axis=1))
print("Произведение:", np.prod(arr, axis=1))

print("\nОсь z:")
print("Среднее:", np.mean(arr, axis=2))
print("Максимум:", np.max(arr, axis=2))
print("Минимум:", np.min(arr, axis=2))
print("Сумма:", np.sum(arr, axis=2))
print("Произведение:", np.prod(arr, axis=2))