In [ ]:
Вопросы
производительности.
Работа со
случайными
числами

In [4]:
import numpy as np

N = 5000
list_2d = [[i + N*j for i in range(N)] for j in range(N)]
array_2d = np.array(list_2d)
array_2d


array([[       0,        1,        2, ...,     4997,     4998,     4999],
       [    5000,     5001,     5002, ...,     9997,     9998,     9999],
       [   10000,    10001,    10002, ...,    14997,    14998,    14999],
       ...,
       [24985000, 24985001, 24985002, ..., 24989997, 24989998, 24989999],
       [24990000, 24990001, 24990002, ..., 24994997, 24994998, 24994999],
       [24995000, 24995001, 24995002, ..., 24999997, 24999998, 24999999]],
      shape=(5000, 5000))

In [6]:
%%timeit
list_2d_mult = [[list_2d[i][j] * list_2d[i][j] for j in range(N)] for i in range(N)]


3.22 s ± 66.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
Это значит, что 3.22 секунды заняло времени плюс-минус 66.5 миллисекунд, пробовал запустить скрипт 7 раз

In [7]:
%%timeit
array_2d_mult = array_2d * array_2d

92 ms ± 4.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
Вывод: функции библиотеки numpy отрабатывают быстрее

In [8]:
print(np.random.rand(5))

[0.43090021 0.21690282 0.20102376 0.18670451 0.36977768]


In [11]:
np.random.seed(42) #нужно, чтобы случайные данные не менялись. 42 - традиция(автостопом по галактике), 
#но можно указать любое.Это некое состояние - всегда делать каким-то определенным образом
print(np.random.rand(5))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [13]:
print(np.random.randint(10, 20, (5, 5))) #указываем shape (размер масива)

[[12 16 17 14 13]
 [17 17 12 15 14]
 [11 17 15 11 14]
 [10 19 15 18 10]
 [19 12 16 13 18]]


In [14]:
print(np.random.normal(size=5))

[ 0.12221917 -0.51543566 -0.60025385  0.94743982  0.291034  ]


In [ ]:
Создайте массив для анализа с помощью генерации чисел из разных распределений.
Посчитайте и сравните средние значения и дисперсии полученных массивов по осям (по столбцам и по строкам).

In [31]:
norm = np.random.normal(1, 2, size = (10000, 20000))
print(norm)

[[ 4.43370286 -0.23649666 -0.37663707 ...  1.67250583 -0.26875807
   0.51590948]
 [ 1.36218096  1.67916199  2.06621329 ...  4.5379979  -1.62428317
   2.56801038]
 [ 2.87198352 -1.92659099  4.80596182 ...  1.87385965  0.45506808
   0.07464627]
 ...
 [ 2.11122336  2.80020339  3.13204108 ...  0.19899646 -1.60395292
  -0.24576413]
 [ 0.71126112  1.63466698 -0.15857388 ...  0.42535946  1.11946278
  -0.93383232]
 [ 1.92500412  1.45196508 -0.54888241 ...  2.75269696  1.57389647
   3.14973276]]


In [28]:
norm.mean(axis = 1) #среднее по строкам

array([0.77578869, 0.85078562, 0.96782281, 0.92268474, 1.14338744,
       1.08947735, 1.18438297, 0.92084248, 0.93303925, 0.9491784 ,
       1.10434007, 0.93500648, 1.1176532 , 1.11613855, 0.8210229 ,
       1.10369207, 0.98150479, 0.85283938, 0.61547773, 1.22558215,
       0.67814104, 1.18082513, 0.87610718, 0.89438153, 1.07601363,
       1.29220023, 1.1006996 , 0.90813013, 0.8541685 , 0.85404045,
       1.04661704, 1.15177374, 0.96767819, 1.09125663, 1.12785897,
       0.85509601, 1.10159279, 1.11037892, 0.87513737, 0.81088044,
       1.00610593, 0.99580902, 1.01909887, 0.86827282, 1.07557279,
       0.93873311, 1.08134066, 0.87204777, 0.791089  , 1.30158262,
       0.94651904, 0.9633069 , 0.97562799, 1.2046882 , 1.05839214,
       0.927513  , 0.81764594, 1.15459741, 1.11911094, 1.05470768,
       1.0359963 , 0.83809629, 1.12710389, 1.00098523, 1.14589058,
       1.18904966, 0.9527501 , 1.02740248, 1.00912506, 1.16732902,
       1.24406735, 0.92764591, 0.73455059, 0.9361757 , 1.12930

In [29]:
norm.mean(axis = 0) #среднее по столбцам

array([0.79110264, 0.92021333, 0.66666883, 0.80188279, 1.05601005,
       1.14117009, 1.05341759, 0.8933664 , 1.36101244, 0.73743211,
       1.30342082, 0.61980009, 1.22444717, 1.16897904, 0.8896414 ,
       0.93057047, 1.03008695, 0.96237272, 0.73003713, 0.96635096,
       0.9719138 , 1.12966855, 1.07309309, 0.99837215, 1.37683178,
       0.9057447 , 0.74125286, 0.69217678, 0.99405343, 0.95522402,
       0.35508565, 1.15463429, 1.11128992, 1.13709019, 1.05536894,
       0.63971193, 0.83007163, 1.37518623, 0.88302891, 0.53961667,
       0.92281863, 0.70488007, 1.21991782, 1.14066005, 0.94227439,
       1.24473169, 0.8602872 , 1.20091355, 0.89617161, 0.55607465,
       0.64126938, 0.61604308, 0.56975177, 0.94249024, 0.87074373,
       1.75498872, 1.29475645, 0.94706524, 0.96570191, 1.12426839,
       1.32313627, 1.10537103, 1.18088302, 0.95465258, 1.02923225,
       1.03478035, 0.91992253, 0.64480096, 1.11085448, 1.08623758,
       1.22811293, 0.6976109 , 1.00421008, 0.99259543, 0.97841

In [26]:
norm.var(axis = 1) #дисперсия по строкам

array([4.58398509, 3.47338578, 3.63695134, 4.08400924, 4.18910146,
       3.80512031, 3.47771444, 3.76292948, 4.42506964, 4.736038  ,
       3.99954078, 4.05724302, 4.12577879, 4.25741134, 3.84271648,
       3.69107833, 3.41076559, 3.20155078, 3.79367013, 4.03804984,
       3.56714576, 3.66645195, 4.3789425 , 3.74194859, 4.38434495,
       4.03230729, 3.83300896, 3.89738287, 3.66954402, 3.46312592,
       3.84971353, 4.28847863, 4.91940442, 3.96896895, 3.66296763,
       4.74929714, 3.29225677, 3.47407754, 3.88064285, 4.50372493,
       3.4889442 , 3.60661896, 3.4973147 , 3.90342263, 4.32819895,
       4.5754555 , 3.47861354, 3.82735172, 3.93692842, 4.12717664,
       4.81863946, 4.14419465, 3.71133455, 3.99177919, 4.43885782,
       3.9624383 , 4.00887164, 4.13333326, 3.34050889, 3.88768389,
       3.38237868, 3.89429645, 4.3575326 , 4.0065278 , 4.71057072,
       3.59945278, 4.24672419, 3.97233621, 3.50845509, 3.89206565,
       3.97984603, 4.28665056, 4.50174024, 4.56669021, 3.80892

In [33]:
norm.var(axis = 0) #дисперсия по столбцам

array([4.0685072 , 3.94157259, 3.94207301, ..., 3.99515267, 3.90842361,
       3.93335047], shape=(20000,))

In [ ]:
Напишите программу, которая:
● Запрашивает у пользователя количество точек данных N.
● Генерирует массив из N случайных точек (координаты x и y), используя нормальное распределение.
● Выводит на экран первые 10 сгенерированных точек (если N было больше 10).
● Вычисляет и выводит среднее значение и стандартное отклонение для координат x и y.


In [40]:
N = int(input('Count:'))

n_arr = np.random.normal(size = (N, 2))
print(n_arr)

print("-------")

mean_arr = n_arr.mean(axis=0)
print(mean_arr)

avg_x = n_arr.mean(axis=0)[0]
print(avg_x)

avg_y = n_arr.mean(axis=0)[1]
print(avg_y)

std_arr = n_arr.std(axis=0)
print(std_arr)

std_x = std_arr[0]
print(std_x)

std_y = std_arr[1]
print(std_y)


Count: 5


[[-0.28743441 -0.4687174 ]
 [ 1.07742578 -1.47326648]
 [ 1.41220232  0.561605  ]
 [-0.81612982  1.07612191]
 [ 0.09325012  1.06845526]]
-------
[0.2958628  0.15283966]
0.29586279753987693
0.15283965555835488
[0.83365097 0.98878162]
0.8336509735232249
0.9887816249312776


In [ ]:
N = int(input("количество точек: "))
n_arr = np.random.normal(size=(N, 2))
print(n_arr)
print("-------")
mean_arr = n_arr.mean(axis=0)
av_x = mean_arr[0]
print(av_x)
av_y = mean_arr[1]
print(av_y)
print("-------")
std_arr = n_arr.std(axis=0)
std_x = std_arr[0]
print(std_x)
std_y = std_arr[1]
print(std_y)