In [ ]:
Python DA Практикум 23

In [1]:
import numpy as np
import pandas as pd

In [ ]:
Задание 1: Создайте numpy-массив из 100 случайных значений. Преобразуйте его в
матрицу 10х10. Вычислите определитель этой матрицы и обратную матрицу.
Транспонируйте исходную матрицу. Перемножьте двумя способами (поэлементно и
матричным умножением) транспонированную матрицу и обратную к исходной.
Любую из матриц преобразуйте в датафрейм pandas. Дайте столбцам названия “A”,
“B”, “C”... Удалите из этого датафрейма последние две строки.

In [2]:
arr = np.random.rand(100)
arr

array([0.74268365, 0.74821918, 0.66361391, 0.100257  , 0.47527635,
       0.76033768, 0.33688557, 0.65473164, 0.14430614, 0.01532053,
       0.92167856, 0.46407936, 0.09719288, 0.49610813, 0.25392862,
       0.5606351 , 0.81527389, 0.15096765, 0.9869728 , 0.61964555,
       0.13040408, 0.4316067 , 0.51068547, 0.69469876, 0.10576694,
       0.52714168, 0.90144017, 0.65483121, 0.43373511, 0.48522702,
       0.86679364, 0.97440094, 0.2423633 , 0.9084428 , 0.9501122 ,
       0.87388849, 0.69240707, 0.15715043, 0.70005134, 0.27377984,
       0.46027526, 0.31824979, 0.08455054, 0.79509509, 0.576686  ,
       0.42052051, 0.01627315, 0.89117451, 0.76567199, 0.58697207,
       0.02148618, 0.69234698, 0.7304363 , 0.49850087, 0.80467603,
       0.51921645, 0.65809166, 0.35914629, 0.63728178, 0.01293182,
       0.01092216, 0.68935701, 0.25938755, 0.16854185, 0.69818907,
       0.95957723, 0.96362288, 0.48853299, 0.6066176 , 0.81438222,
       0.73644906, 0.09153286, 0.22700098, 0.7041364 , 0.61943

In [3]:
matrix = arr.reshape(10,10)
matrix

array([[0.74268365, 0.74821918, 0.66361391, 0.100257  , 0.47527635,
        0.76033768, 0.33688557, 0.65473164, 0.14430614, 0.01532053],
       [0.92167856, 0.46407936, 0.09719288, 0.49610813, 0.25392862,
        0.5606351 , 0.81527389, 0.15096765, 0.9869728 , 0.61964555],
       [0.13040408, 0.4316067 , 0.51068547, 0.69469876, 0.10576694,
        0.52714168, 0.90144017, 0.65483121, 0.43373511, 0.48522702],
       [0.86679364, 0.97440094, 0.2423633 , 0.9084428 , 0.9501122 ,
        0.87388849, 0.69240707, 0.15715043, 0.70005134, 0.27377984],
       [0.46027526, 0.31824979, 0.08455054, 0.79509509, 0.576686  ,
        0.42052051, 0.01627315, 0.89117451, 0.76567199, 0.58697207],
       [0.02148618, 0.69234698, 0.7304363 , 0.49850087, 0.80467603,
        0.51921645, 0.65809166, 0.35914629, 0.63728178, 0.01293182],
       [0.01092216, 0.68935701, 0.25938755, 0.16854185, 0.69818907,
        0.95957723, 0.96362288, 0.48853299, 0.6066176 , 0.81438222],
       [0.73644906, 0.09153286, 0.2270009

In [6]:
t_matrix = np.linalg.inv(matrix)
t_matrix

array([[  0.42770046,  -0.10269191,  -0.16100583,   0.48066283,
          0.08973634,  -0.80267383,  -0.24398191,   0.1853656 ,
          0.67115435,  -0.28060768],
       [  1.81783395,  -1.95376722,  -0.65211145,   0.9194482 ,
          4.43332245,  -0.51928417,   3.80229461,  -2.8213858 ,
          0.77306751,  -4.6047096 ],
       [ -2.69478529,   4.27242454,   3.25140806,  -0.81619106,
        -11.26484634,   0.57142007,  -9.97621338,   4.21996353,
         -2.45710371,  12.22910558],
       [ -1.36315644,   0.79779307,   1.62873281,   0.57519054,
         -2.8496075 ,  -0.0677995 ,  -3.1269252 ,   1.17614118,
         -0.91425248,   3.32345076],
       [ -0.17893443,  -1.76153776,  -0.98520135,   0.96625688,
          1.19770748,  -0.31639148,   1.25482733,   0.15338847,
          1.40356899,  -1.34869911],
       [ -1.34639303,   3.62169628,   1.01687348,  -1.34793124,
         -6.06465266,   1.10277947,  -4.56519423,   2.54495478,
         -2.97779615,   6.53632567],
       [  

In [7]:
det = np.linalg.det(matrix)
print(det)
det_2 = np.linalg.det(t_matrix)
det_2
det_2 * det

0.01612704085760335


np.float64(0.9999999999999973)

In [8]:
matrix @ t_matrix

array([[ 1.00000000e+00, -5.24344957e-16, -8.55378114e-17,
         9.88419606e-17,  1.05200311e-15,  1.56408316e-16,
         1.18655176e-15, -5.62344030e-17,  1.06758163e-15,
        -5.12898096e-16],
       [-5.42450231e-17,  1.00000000e+00,  1.59964394e-16,
        -3.68950233e-17,  1.59113702e-16, -7.83466360e-17,
        -1.22890843e-16,  5.38494572e-17, -1.30801421e-16,
         1.50334710e-16],
       [ 2.63257755e-17, -3.09856505e-16,  1.00000000e+00,
        -5.89595471e-17, -1.51737925e-16, -1.97186331e-16,
         6.39924084e-16, -1.09800041e-16,  4.28585980e-16,
        -1.86273055e-15],
       [-6.08714007e-16,  9.21680350e-16,  9.73842908e-16,
         1.00000000e+00, -2.50366103e-15, -3.04340169e-16,
        -1.01645800e-15,  3.02992298e-16, -1.21609025e-15,
         1.90978762e-15],
       [-1.88997421e-16,  1.42283074e-16,  5.75214401e-16,
        -2.12773803e-16,  1.00000000e+00,  2.26706070e-16,
         6.77378998e-16, -2.05238363e-16, -1.44207427e-15,
        -1.

In [10]:
tr_matrix = matrix.T
tr_matrix

array([[0.74268365, 0.92167856, 0.13040408, 0.86679364, 0.46027526,
        0.02148618, 0.01092216, 0.73644906, 0.38292188, 0.11953025],
       [0.74821918, 0.46407936, 0.4316067 , 0.97440094, 0.31824979,
        0.69234698, 0.68935701, 0.09153286, 0.35153032, 0.81523392],
       [0.66361391, 0.09719288, 0.51068547, 0.2423633 , 0.08455054,
        0.7304363 , 0.25938755, 0.22700098, 0.58943311, 0.36990003],
       [0.100257  , 0.49610813, 0.69469876, 0.9084428 , 0.79509509,
        0.49850087, 0.16854185, 0.7041364 , 0.02403202, 0.3331478 ],
       [0.47527635, 0.25392862, 0.10576694, 0.9501122 , 0.576686  ,
        0.80467603, 0.69818907, 0.6194345 , 0.46450631, 0.99406795],
       [0.76033768, 0.5606351 , 0.52714168, 0.87388849, 0.42052051,
        0.51921645, 0.95957723, 0.98574477, 0.03711086, 0.70305359],
       [0.33688557, 0.81527389, 0.90144017, 0.69240707, 0.01627315,
        0.65809166, 0.96362288, 0.5362924 , 0.75683419, 0.33329384],
       [0.65473164, 0.15096765, 0.6548312

In [11]:
tr_matrix * t_matrix

array([[ 3.17646143e-01, -9.46489285e-02, -2.09958175e-02,
         4.16635485e-01,  4.13034156e-02, -1.72463909e-02,
        -2.66480838e-03,  1.36512324e-01,  2.56999684e-01,
        -3.35411056e-02],
       [ 1.36013822e+00, -9.06703044e-01, -2.81455670e-01,
         8.95911198e-01,  1.41090396e+00, -3.59524821e-01,
         2.62113843e+00, -2.58249510e-01,  2.71756673e-01,
        -3.75391544e+00],
       [-1.78829699e+00,  4.15249225e-01,  1.66044684e+00,
        -1.97814756e-01, -9.52448842e-01,  4.17385962e-01,
        -2.58770559e+00,  9.57935860e-01, -1.44829828e+00,
         4.52354657e+00],
       [-1.36665976e-01,  3.95791631e-01,  1.13147866e+00,
         5.22527704e-01, -2.26570895e+00, -3.37981100e-02,
        -5.27017765e-01,  8.28163816e-01, -2.19713352e-02,
         1.10720032e+00],
       [-8.50432998e-02, -4.47304845e-01, -1.04201736e-01,
         9.18052446e-01,  6.90701138e-01, -2.54592643e-01,
         8.76106726e-01,  9.50141116e-02,  6.51966656e-01,
        -1.

In [12]:
df = pd.DataFrame(tr_matrix, columns=list('ABCDEFGHIJ'))
df

A         B         C         D         E         F         G  \
0  0.742684  0.921679  0.130404  0.866794  0.460275  0.021486  0.010922   
1  0.748219  0.464079  0.431607  0.974401  0.318250  0.692347  0.689357   
2  0.663614  0.097193  0.510685  0.242363  0.084551  0.730436  0.259388   
3  0.100257  0.496108  0.694699  0.908443  0.795095  0.498501  0.168542   
4  0.475276  0.253929  0.105767  0.950112  0.576686  0.804676  0.698189   
5  0.760338  0.560635  0.527142  0.873888  0.420521  0.519216  0.959577   
6  0.336886  0.815274  0.901440  0.692407  0.016273  0.658092  0.963623   
7  0.654732  0.150968  0.654831  0.157150  0.891175  0.359146  0.488533   
8  0.144306  0.986973  0.433735  0.700051  0.765672  0.637282  0.606618   
9  0.015321  0.619646  0.485227  0.273780  0.586972  0.012932  0.814382   

          H         I         J  
0  0.736449  0.382922  0.119530  
1  0.091533  0.351530  0.815234  
2  0.227001  0.589433  0.369900  
3  0.704136  0.024032  0.333148  
4  0.619435  0.464506  0.994068  
5  0.985745  0.037111  0.703054  
6  0.536292  0.756834  0.333294  
7  0.797500  0.301031  0.915863  
8  0.247759  0.838070  0.871666  
9  0.248523  0.548136  0.904969

In [15]:
df_1 = df.iloc[:-2]
df_1

A         B         C         D         E         F         G  \
0  0.742684  0.921679  0.130404  0.866794  0.460275  0.021486  0.010922   
1  0.748219  0.464079  0.431607  0.974401  0.318250  0.692347  0.689357   
2  0.663614  0.097193  0.510685  0.242363  0.084551  0.730436  0.259388   
3  0.100257  0.496108  0.694699  0.908443  0.795095  0.498501  0.168542   
4  0.475276  0.253929  0.105767  0.950112  0.576686  0.804676  0.698189   
5  0.760338  0.560635  0.527142  0.873888  0.420521  0.519216  0.959577   
6  0.336886  0.815274  0.901440  0.692407  0.016273  0.658092  0.963623   
7  0.654732  0.150968  0.654831  0.157150  0.891175  0.359146  0.488533   

          H         I         J  
0  0.736449  0.382922  0.119530  
1  0.091533  0.351530  0.815234  
2  0.227001  0.589433  0.369900  
3  0.704136  0.024032  0.333148  
4  0.619435  0.464506  0.994068  
5  0.985745  0.037111  0.703054  
6  0.536292  0.756834  0.333294  
7  0.797500  0.301031  0.915863

In [ ]:
Задание 2: Рассчитайте среднее значение и стандартное отклонение каждого
признака для каждого вида в наборе данных Iris.

In [13]:
import seaborn as sns

In [16]:
iris = sns.load_dataset('iris')
display(iris)

iris.groupby('species').agg(['mean', 'std'])

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

sepal_length           sepal_width           petal_length  \
                   mean       std        mean       std         mean   
species                                                                
setosa            5.006  0.352490       3.428  0.379064        1.462   
versicolor        5.936  0.516171       2.770  0.313798        4.260   
virginica         6.588  0.635880       2.974  0.322497        5.552   

                     petal_width            
                 std        mean       std  
species                                     
setosa      0.173664       0.246  0.105386  
versicolor  0.469911       1.326  0.197753  
virginica   0.551895       2.026  0.274650

In [ ]:
Задача 3: Рассчитайте среднюю сумму чаевых для каждой комбинации дня и
времени (обед/ужин) в наборе данных Tips.

In [18]:
tips = sns.load_dataset('tips')
display(tips)

tips.groupby(['day', 'time'])['tip'].mean()

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

C:\Users\user\AppData\Local\Temp\ipykernel_31684\380639743.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(['day', 'time'])['tip'].mean()


day   time  
Thur  Lunch     2.767705
      Dinner    3.000000
Fri   Lunch     2.382857
      Dinner    2.940000
Sat   Lunch          NaN
      Dinner    2.993103
Sun   Lunch          NaN
      Dinner    3.255132
Name: tip, dtype: float64

In [ ]:
Задача 4: Рассчитайте ежегодный темп роста числа пассажиров в наборе данных
Flights.

In [25]:
flights = sns.load_dataset('flights')
display(flights)

flights_year = flights.groupby('year').passengers.sum()
display(flights_year)
flights_year.pct_change()* 100

year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

year
1949    1520
1950    1676
1951    2042
1952    2364
1953    2700
1954    2867
1955    3408
1956    3939
1957    4421
1958    4572
1959    5140
1960    5714
Name: passengers, dtype: int64

year
1949          NaN
1950    10.263158
1951    21.837709
1952    15.768854
1953    14.213198
1954     6.185185
1955    18.869899
1956    15.580986
1957    12.236608
1958     3.415517
1959    12.423447
1960    11.167315
Name: passengers, dtype: float64

In [ ]:
Задача 5: Создайте возрастные группы и рассчитайте коэффициент выживаемости
для каждой возрастной группы в наборе данных Titanic.

In [29]:
titanic = sns.load_dataset('titanic')
display(titanic)

range_age = [0, 18, 35, 55, 85, 120]
name_age = ['child', 'young', 'adult', 'middle aged', 'aged']
titanic['age_group'] = pd.cut(titanic.age, bins = range_age, labels=name_age)
titanic.groupby('age_group')['survived'].mean() * 100


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

C:\Users\user\AppData\Local\Temp\ipykernel_31684\1087833807.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby('age_group')['survived'].mean() * 100


age_group
child          50.359712
young          38.268156
adult          40.112994
middle aged    30.000000
aged                 NaN
Name: survived, dtype: float64

In [ ]:
Задача 6: Рассчитайте коэффициент выживаемости для каждого сочетания класса и пола в наборе данных Titanic.

In [30]:
survival_rates = titanic.groupby(['class', 'sex'])['survived'].mean() * 100
survival_rates

C:\Users\user\AppData\Local\Temp\ipykernel_31684\714053077.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  survival_rates = titanic.groupby(['class', 'sex'])['survived'].mean() * 100


class   sex   
First   female    96.808511
        male      36.885246
Second  female    92.105263
        male      15.740741
Third   female    50.000000
        male      13.544669
Name: survived, dtype: float64

In [ ]:
Задача 7: Нормализуйте признаки (sepal_length, sepal_width, petal_length, petal_width)
с помощью Z-score нормализации в наборе данных Iris.

In [31]:
survival_rates = titanic.groupby(['class', 'sex'])['survived'].mean() * 100
survival_rates

C:\Users\user\AppData\Local\Temp\ipykernel_31684\714053077.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  survival_rates = titanic.groupby(['class', 'sex'])['survived'].mean() * 100


class   sex   
First   female    96.808511
        male      36.885246
Second  female    92.105263
        male      15.740741
Third   female    50.000000
        male      13.544669
Name: survived, dtype: float64

In [33]:
data = sns.load_dataset("iris")
features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
display(features)
data_normalized = (data[features] - data[features].mean()) / data[features].std()
data_normalized

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

sepal_length  sepal_width  petal_length  petal_width
0       -0.897674     1.015602     -1.335752    -1.311052
1       -1.139200    -0.131539     -1.335752    -1.311052
2       -1.380727     0.327318     -1.392399    -1.311052
3       -1.501490     0.097889     -1.279104    -1.311052
4       -1.018437     1.245030     -1.335752    -1.311052
..            ...          ...           ...          ...
145      1.034539    -0.131539      0.816859     1.443994
146      0.551486    -1.278680      0.703564     0.919223
147      0.793012    -0.131539      0.816859     1.050416
148      0.430722     0.786174      0.930154     1.443994
149      0.068433    -0.131539      0.760211     0.788031

[150 rows x 4 columns]

In [ ]:
Задача 8: Рассчитайте диапазон (max - min) каждого признака для каждого вида в
наборе данных Iris.

In [34]:
iris.groupby('species').agg(lambda x: x.max() - x.min())

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               1.5          2.1           0.9          0.5
versicolor           2.1          1.4           2.1          0.8
virginica            3.0          1.6           2.4          1.1

In [ ]:
Задача 9: Заполните недостающие значения в столбце "Возраст" медианным
возрастом пассажиров того же класса и пола в наборе данных Titanic.

In [35]:
titanic = sns.load_dataset('titanic')
display(titanic)

median_age = titanic.groupby(['class', 'sex']).age.median().reset_index()
df = titanic.merge(median_age, on = ['class', 'sex'])
df.age_x.isnull().sum()
df.age_y.isnull().sum()

df.age_x = df.age_x.fillna(df.age_y)
df.age_x.isnull().sum()
df.drop('age_y', axis = 1).rename(columns = {'age_x': 'age'})

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

C:\Users\user\AppData\Local\Temp\ipykernel_31684\3097479469.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  median_age = titanic.groupby(['class', 'sex']).age.median().reset_index()


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female  21.5      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [ ]:
Рассчитайте общий счет и средний процент чаевых для каждого дня в наборе данных Tips.

In [36]:
tips = sns.load_dataset('tips')

tips["persent"] = tips.tip / tips.total_bill*100
display(tips)
tips.groupby("day").agg({"total_bill":"sum", "persent":"mean"})

total_bill   tip     sex smoker   day    time  size    persent
0         16.99  1.01  Female     No   Sun  Dinner     2   5.944673
1         10.34  1.66    Male     No   Sun  Dinner     3  16.054159
2         21.01  3.50    Male     No   Sun  Dinner     3  16.658734
3         23.68  3.31    Male     No   Sun  Dinner     2  13.978041
4         24.59  3.61  Female     No   Sun  Dinner     4  14.680765
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3  20.392697
240       27.18  2.00  Female    Yes   Sat  Dinner     2   7.358352
241       22.67  2.00    Male    Yes   Sat  Dinner     2   8.822232
242       17.82  1.75    Male     No   Sat  Dinner     2   9.820426
243       18.78  3.00  Female     No  Thur  Dinner     2  15.974441

[244 rows x 8 columns]

C:\Users\user\AppData\Local\Temp\ipykernel_31684\2934135829.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby("day").agg({"total_bill":"sum", "persent":"mean"})


total_bill    persent
day                        
Thur     1096.33  16.127563
Fri       325.88  16.991303
Sat      1778.40  15.315172
Sun      1627.16  16.689729