Создание массивов в NumPy

In [1]:
import numpy as np

In [3]:
np.array(object, dtype=None, copy=True, order='K', ndmin=0)

array(<class 'object'>, dtype=object)

In [4]:
import numpy as np
# Создание одномерного массива из списка
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Массив из списка:", array_from_list)
# Создание одномерного массива из кортежа
tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)
print("Массив из кортежа:", array_from_tuple)
# Создание двумерного массива из списка списков
list_of_lists = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_of_lists)
print("Двумерный массив из списка списков:\n", array_2d)

Массив из списка: [1 2 3 4 5]
Массив из кортежа: [ 6  7  8  9 10]
Двумерный массив из списка списков:
 [[1 2 3]
 [4 5 6]]


In [ ]:
Атрибуты массивов
в NumPy

In [5]:
# Создание одномерного массива
array1 = np.array([1, 2, 3])
print(array1.ndim) # Вывод: 1
# Создание двумерного массива
array2 = np.array([[2, 3, 4], [5, 6, 7]])
print(array2.ndim)

1
2


In [6]:
# Создание одномерного массива
array1 = np.array([1, 2, 3])
print(array1.shape) # Вывод: (3,)
# Создание двумерного массива
array2 = np.array([[3, 4, 5], [6, 7, 8]])
print(array2.shape)

(3,)
(2, 3)


In [7]:
# Создание одномерного массива
array1 = np.array([1, 2, 3])
print(array1.size) # Выходные данные: 3
# Создание двумерного массива
array2 = np.array([[3, 5, 7], [8, 9, 10]])
print(array2.size) 

3
6


In [8]:
# Создание массива целых чисел
array1 = np.array([10, 20, 30])
print(array1.dtype) # Выходные данные: int64
# Создание массива строк
array2 = np.array(["Python", "NumPy", "Data"])
print(array2.dtype) 

int64
<U6


In [9]:
# Создание массива 64-битных целых чисел
array1 = np.array([1, 2, 3], dtype=np.int64)
print(array1.itemsize) # Выходные данные: 8
# Создание массива 32-битных целых чисел
array2 = np.array([1, 2, 3], dtype=np.int32)
print(array2.itemsize)

8
4


In [10]:
# Создание одномерного массива из списка
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Массив из списка:", array_from_list)
# Создание одномерного массива из кортежа
tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)
print("Массив из кортежа:", array_from_tuple)
# Создание двумерного массива из списка списков
list_of_lists = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_of_lists)
print("Двумерный массив из списка списков:\n", array_2d)

Массив из списка: [1 2 3 4 5]
Массив из кортежа: [ 6  7  8  9 10]
Двумерный массив из списка списков:
 [[1 2 3]
 [4 5 6]]


In [11]:
# Создание одномерного массива единиц
array1 = np.ones(5)
print("одномерный массив единиц:", array1)
# Создание двумерного массива единиц
array2 = np.ones((3, 4))
print("Двумерный массив единиц:\n", array2)

одномерный массив единиц: [1. 1. 1. 1. 1.]
Двумерный массив единиц:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# Создание одномерного массива, заполненного значением 7
array1 = np.full(5, 7)
print("Одномерный массив, заполненный значением 7:",
array1)
# Создание двумерного массива, заполненного значением
3,14
array2 = np.full((3, 4), 3.14)
print("Двумерный массив, заполненный значением 3.14:\n",
array2)


Одномерный массив, заполненный значением 7: [7 7 7 7 7]
Двумерный массив, заполненный значением 3.14:
 [[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]


In [ ]:
Инициализация
массивов

In [13]:
# Создание массива со значениями от 0 до 9
array1 = np.arange(10)
print("Массив со значениями от 0 до 9:", array1)
# Создание массива со значениями от 1 до 9
array2 = np.arange(1, 10)
print("Массив со значениями от 1 до 9:", array2)
# Создание массива со значениями от 1 до 9 с шагом 2
array3 = np.arange(1, 10, 2)
print("Массив со значениями от 1 до 9 с шагом 2:", array3)
# Создание массива со значениями с плавающей точкой
array4 = np.arange(0, 1, 0.1)
print("Массив со значениями с плавающей точкой от 0 до 1 с шагом 0,1:", array4)

Массив со значениями от 0 до 9: [0 1 2 3 4 5 6 7 8 9]
Массив со значениями от 1 до 9: [1 2 3 4 5 6 7 8 9]
Массив со значениями от 1 до 9 с шагом 2: [1 3 5 7 9]
Массив со значениями с плавающей точкой от 0 до 1 с шагом 0,1: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [14]:
# Создание массива с 10 равномерно распределенными значениями от 0 до 1
array1 = np.linspace(0, 1, 10)
print("Массив с 10 равномерно распределенными значениями от 0 до 1:", array1)

# Создание массива с 5 равномерно распределенными значениями от 1 до 10
array2 = np.linspace(1, 10, 5)
print("Массив с 5 равномерно распределенными значениями от 1 до 10:", array2)

# Создание массива с 5 равномерно распределенными значениями от 1 до 10, исключая конечную точку
array3 = np.linspace(1, 10, 5, endpoint=False)
print("Массив с 5 равномерно распределенными значениями от 1 до 10, исключая конечную точку:", array3)

# Создание массива и возвращение размера шага
array4, step = np.linspace(0, 1, 5, retstep=True)
print("Массив с 5 равномерно расположенными значениями от 0 до 1:", array4)
print("Размер шага:", step)

Массив с 10 равномерно распределенными значениями от 0 до 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Массив с 5 равномерно распределенными значениями от 1 до 10: [ 1.    3.25  5.5   7.75 10.  ]
Массив с 5 равномерно распределенными значениями от 1 до 10, исключая конечную точку: [1.  2.8 4.6 6.4 8.2]
Массив с 5 равномерно расположенными значениями от 0 до 1: [0.   0.25 0.5  0.75 1.  ]
Размер шага: 0.25


In [ ]:
Арифметические
операции в NumPy

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b
print(result)

[5 7 9]


In [16]:
result = np.add(a, b) # когдав функцию нужно передать функцию, + не получится передать
print(result)

[5 7 9]


In [17]:
result = a - b # используем всегда "-", пока не нужно передать функцию
print(result) 

[-3 -3 -3]


In [18]:
result = np.subtract(a, b)
print(result) 

[-3 -3 -3]


In [19]:
result = a * b
print(result) 

[ 4 10 18]


In [20]:
result = np.multiply(a, b)
print(result)

[ 4 10 18]


In [21]:
result = a / b
print(result)

[0.25 0.4  0.5 ]


In [22]:
result = np.divide(a, b)
print(result)

[0.25 0.4  0.5 ]


In [23]:
result= a ** b
print(result) 

[  1  32 729]


In [24]:
result = np.power(a, b)
print(result)

[  1  32 729]


In [ ]:
Все базовые операции выполняются поэлементно

In [ ]:
Правила broadcasting’а

● Если массивы не имеют одинакового количества измерений, добавляйте 1 к форме
меньшего массива до тех пор, пока обе формы не станут одинаковой длины.
● Массивы совместимы для broadcasting’а, если для каждой размерности их размеры
либо одинаковы, либо один из них равен 1.
● Результирующая форма массива - это максимальный размер по каждому измерению
входных массивов.

In [26]:
# Массив a формы (3, 1)
a = np.array([[1], [2], [3]])
# Массив b формы (1, 4)
b = np.array([4, 5, 6, 7])
# Передача a и b в форму (3, 4)
result = a + b
print(result)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


Операции над матрицами

In [31]:
# Создание двух матриц
matrix1 = np.array([[1, 3], [5, 7]])
matrix2 = np.array([[2, 6], [4, 8]])
print(matrix1)
print(matrix2)

# Умножение матриц
result = np.dot(matrix1, matrix2)
print("Матричное умножение:\n", result)


[[1 3]
 [5 7]]
[[2 6]
 [4 8]]
Матричное умножение:
 [[14 30]
 [38 86]]


In [32]:
# Создание матрицы
matrix = np.array([[1, 3], [5, 7]])
# Транспонирование матрицы
transpose = np.transpose(matrix)
print("Транспонирование:\n", transpose)

Транспонирование:
 [[1 5]
 [3 7]]


In [ ]:
Изменение формы и
размера массивов
в NumPy

In [33]:
# 1D в 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print("От 1D к 2D:\n", newarr)
# 1D в 3D
newarr = arr.reshape(2, 3, 2)
print("От 1D к 3D:\n", newarr)
# Использование -1 для неизвестной размерности
newarr = arr.reshape(2, 2, -1)
print("Использование -1 для неизвестной размерности:\n", newarr)

От 1D к 2D:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
От 1D к 3D:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Использование -1 для неизвестной размерности:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [34]:
# Исходный массив
arr = np.array([[0, 1], [2, 3]])
# Изменение размера массива в большую сторону
resized_arr = np.resize(arr, (2, 3))
print("Изменен размер массива на больший:\n", resized_arr)
# Изменение размера массива в меньшую сторону
resized_arr = np.resize(arr, (1, 4))
print("Изменен размер массива на меньший:\n", resized_arr)

Изменен размер массива на больший:
 [[0 1 2]
 [3 0 1]]
Изменен размер массива на меньший:
 [[0 1 2 3]]


In [35]:
# Исходный одномерный массив
arr = np.array([1, 2, 3])
# Добавление новой оси
newarr = arr[:, np.newaxis]
print("Добавление новой оси с помощью np.newaxis:\n", newarr)

Добавление новой оси с помощью np.newaxis:
 [[1]
 [2]
 [3]]


In [ ]:
Случайные числа
в NumPy

In [36]:
# Генерация одного случайного числа
random_number = np.random.rand()
print("Одиночное случайное число:", random_number)

# Генерация одномерного массива случайных чисел
random_array_1d = np.random.rand(5)
print("Одномерный массив случайных чисел:", random_array_1d)

# Генерация двумерного массива случайных чисел
random_array_2d = np.random.rand(3, 4)
print("Двумерный массив случайных чисел:\n", random_array_2d)

Одиночное случайное число: 0.36207459968768174
Одномерный массив случайных чисел: [0.95775142 0.29421966 0.66108523 0.62778517 0.66088336]
Двумерный массив случайных чисел:
 [[0.49563006 0.46451123 0.70012063 0.83579579]
 [0.06923061 0.21509291 0.71220086 0.21646634]
 [0.59506777 0.85498821 0.43050171 0.62993554]]


In [37]:
# Генерация одного случайного числа из стандартного нормального распределения
random_number = np.random.randn()
print("Одиночное случайное число из стандартного нормального распределения:", random_number)

# Генерация одномерного массива случайных чисел из стандартного нормального распределения
random_array_1d = np.random.randn(5)
print("1D массив случайных чисел из стандартного нормального распределения:", random_array_1d)

# Генерирование двумерного массива случайных чисел из стандартного нормального распределения
random_array_2d = np.random.randn(3, 4)
print("Двумерный массив случайных чисел из стандартного нормального распределения:\n",
random_array_2d)

Одиночное случайное число из стандартного нормального распределения: -0.6228721691175431
1D массив случайных чисел из стандартного нормального распределения: [ 1.30347225  0.639693    1.42864467 -0.09550928  0.51946621]
Двумерный массив случайных чисел из стандартного нормального распределения:
 [[-0.57839054  0.02865901  0.58113294  0.18124356]
 [-0.53095152 -0.30531344  1.0885241   1.94782781]
 [ 0.79203095 -0.27332492 -0.48273965 -0.68394919]]


In [38]:
# Генерация одного случайного целого числа
random_int = np.random.randint(10)
print("Одиночное случайное целое число:", random_int)

# Генерация одномерного массива случайных целых чисел
random_array_1d = np.random.randint(1, 10, 5)
print("1D массив случайных целых чисел:", random_array_1d)

# Генерирование двумерного массива случайных целых чисел
random_array_2d = np.random.randint(1, 10, (3, 4))
print("Двумерный массив случайных целых чисел:\n", random_array_2d)

Одиночное случайное целое число: 1
1D массив случайных целых чисел: [6 6 9 8 7]
Двумерный массив случайных целых чисел:
 [[6 6 1 8]
 [9 2 9 3]
 [5 1 5 7]]


In [39]:
# Создание массива
arr = np.array([1, 2, 3, 4, 5])

# Случайный выбор одного элемента
random_choice = np.random.choice(arr)
print("Случайно выбранный элемент:", random_choice)

# Случайный выбор нескольких элементов с заменой
random_choices = np.random.choice(arr, size=3, replace=True)
print("Случайно выбранные элементы с заменой:", random_choices)

# Случайный выбор нескольких элементов без замены
random_choices = np.random.choice(arr, size=3, replace=False)
print("Случайный выбор элементов без замены:", random_choices)

# Случайный выбор элементов с заданными вероятностями
random_choices = np.random.choice(arr, size=3, p=[0.1, 0.2, 0.3, 0.2, 0.2])
print("Случайно выбранные элементы с заданными вероятностями:", random_choices)

Случайно выбранный элемент: 5
Случайно выбранные элементы с заменой: [2 3 1]
Случайный выбор элементов без замены: [2 3 5]
Случайно выбранные элементы с заданными вероятностями: [2 2 5]


In [40]:
# Установка семени
np.random.seed(42)

# Генерация случайных чисел
random_array_1 = np.random.rand(3)
print("Случайный массив 1:", random_array_1)

# Сброс затравки
np.random.seed(42)

# Снова генерируем случайные числа
random_array_2 = np.random.rand(3)
print("Случайный массив 2:", random_array_2)

Случайный массив 1: [0.37454012 0.95071431 0.73199394]
Случайный массив 2: [0.37454012 0.95071431 0.73199394]


In [ ]:
Создайте одномерный массив, преобразуйте его в двумерный, а затем “сплющите” обратно в одномерный.

In [45]:
array_1d = np.arange(1, 13)
print("1D array:", array_1d)

array_2d = array_1d.reshape(3, 4)
print("2D array:\n", array_2d)

flattened_array = array_2d.flatten()
print("Flattened array:", flattened_array)

print(array_2d.reshape(array_2d.size))

1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
2. Сгенерируйте случайный массив и рассчитайте базовую статистику.

In [47]:
np.random.seed(42)
random_array = np.random.rand(4, 5)
print("Random array:\n", random_array)
mean_value = np.mean(random_array)
median_value = np.median(random_array)
std_deviation = np.std(random_array)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Mean value:", mean_value)
print("Standard deviation:", std_deviation)
print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Median value:", median_value)

Random array:
 [[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]
Mean value: 0.4577022883977855
Standard deviation: 0.29989606193622076
Minimum value: 0.020584494295802447
Maximum value: 0.9699098521619943
Median value: 0.4032425687447391
