hW_02_AGrid

1. Индексация массивов NumPy:


Напишите программу, которая:

- Запрашивает у пользователя ввод одномерного массива, элементы которого вводятся в виде чисел, разделенных пробелами.

- Преобразует введенную строку в массив NumPy.

- Запрашивает у пользователя индекс элемента, который необходимо извлечь из массива.

- Выводит значение элемента по запрошенному индексу.

- Запрашивает у пользователя ввод диапазона индексов в формате `начало:конец`, чтобы извлечь срез массива.

- Выводит срез массива.


Пример вывода:


Введите массив: 1 2 3 4 5

Введите индекс элемента: 2

Элемент с индексом 2: 3

Введите диапазон индексов (начало:конец): 1:4

Срез массива: [2 3 4]

In [1]:
import numpy as np

arr_input = input('Array: ')
arr = np.array(list(map(int, arr_input.split())))

Array:  1 2 3 4 5


In [3]:
i = int(input('Index: '))
num = arr[i]

print(f'Element with index {i}: {num}')

Index:  2


Element with index 2: 3


In [4]:
i_slice = input('Slice(with a ":" between the numbers: )').split(':')
slice = list(map(int, i_slice))
slice = arr[slice[0]:slice[1]]

print(f'Slice of array: {slice}')

Slice(with a ":" between the numbers: ) 1:4


Slice of array: [2 3 4]


2. Операции с матрицами в NumPy:


Напишите программу, которая:

- Запрашивает у пользователя размеры матрицы MxN.

- Генерирует две матрицы указанных размеров, заполненные случайными числами от 0 до 9.

- Выводит обе сгенерированные матрицы на экран.

- Выполняет и выводит результат одной из следующих операций (на выбор пользователя): сложение матриц, умножение матриц, транспонирование одной из матриц.

- Если выбрано умножение, убедитесь, что размеры матриц соответствуют правилам матричного умножения.


Пример вывода:


Введите размеры матрицы MxN: 2x3


Первая матрица:

[[1 2 3]

 [4 5 6]]


Вторая матрица:

[[6 5 4]

 [3 2 1]]


Выберите операцию (сложение, умножение, транспонирование): сложение


Результ сложения:

[[ 7  7  7]

 [ 7  7  7]]



In [43]:
print('Введите размеры матрицы M x N')
m = int(input('M = '))
n = int(input('N = '))
mn = m * n

Введите размеры матрицы M x N


M =  4
N =  3


In [44]:
A = np.random.randint(0, 10, size=mn).reshape(m, n)
B = np.random.randint(0, 10, size=mn).reshape(m, n)

print('Matrix A')
print(A)
print()
print('Matrix B')
print(B)

Matrix A
[[7 8 0]
 [1 4 2]
 [9 5 9]
 [1 6 4]]

Matrix B
[[7 9 9]
 [5 5 8]
 [4 4 9]
 [2 4 8]]


In [47]:
w = int(input('''Выберите операцию:
        1 - сложение,
        2 - поэлементное умножение,
        3 - матричное умножение,
        4 - транспонирование): '''))

Выберите операцию:
        1 - сложение,
        2 - поэлементное умножение,
        3 - матричное умножение,
        4 - транспонирование):  4


In [48]:
if w == 1:
    print(f'Результат сложения:\n{A + B}')

elif w == 2:
    if A.shape == B.shape:
        print(f'Результат поэлементного умножения:\n{A * B}')
    else:
        print('Ошибка: размеры матриц не совпадают для поэлементного умножения.')

elif w == 3:
    if A.shape[1] == B.shape[0]:
        print(f'Результат матричного умножения:\n{A @ B}')
    else:
        print('Ошибка: размеры матриц не соответствуют для матричного умножения.')

elif w == 4:
    M = input('Какую матрицу транспонировать? A/B: ').lower()
    if M == 'a':
        print(f'Результат транспонирования матрицы A:\n{A.T}')
    elif M == 'b':
        print(f'Результат транспонирования матрицы B:\n{B.T}')
    else:
        print('Неверный ввод. Введите "A" или "B".')

else:
    print('Неправильный ввод. Введите цифру от 1 до 4.')

Какую матрицу транспонировать? A/B:  a


Результат транспонирования матрицы A:
[[7 1 9 1]
 [8 4 5 6]
 [0 2 9 4]]
