In [ ]:
1. Сложение двух массивов:

   Напишите программу, которая:

   - Запрашивает у пользователя ввод двух одномерных массивов одинаковой длины. Массивы вводятся в виде чисел, разделенных пробелами.

   - Преобразует введенные строки в массивы NumPy.

   - Складывает два массива поэлементно.

   - Выводит результат сложения на экран.


In [1]:
import numpy as np

n = list(map(int, input().split()))
m = list(map(int, input().split()))

first_array = np.array(n)
second_array = np.array(m)
print(first_array, second_array)
print(first_array + second_array)



 1 2 3 4
 5 6 7 8


[1 2 3 4] [5 6 7 8]
[ 6  8 10 12]


In [ ]:
2. Поэлементное умножение массивов:

   Напишите программу, которая:

   - Запрашивает у пользователя размер массивов N.

   - Генерирует два одномерных массива длины N с случайными целыми числами от 1 до 10.

   - Выводит оба сгенерированных массива на экран.

   - Выполняет поэлементное умножение массивов.

   - Выводит результат умножения на экран.


In [3]:
import random as rd

n = int(input())
first_list = [int(rd.uniform(1, 10)) for i in range(n)]
second_list = [int(rd.uniform(1, 10)) for i in range(n)]

first_array = np.array(first_list)
second_array = np.array(second_list)
print(first_array, second_array)
print(first_array * second_array)

 3


[6 7 1] [9 3 5]
[54 21  5]


In [ ]:
3. Создание и модификация массива:

   Напишите программу, которая:

   - Запрашивает у пользователя количество элементов массива N.

   - Генерирует одномерный массив длины N, заполненный случайными числами от 0 до 100.

   - Выводит сгенерированный массив на экран.

   - Запрашивает у пользователя число X.

   - Умножает каждый элемент массива на число X.

   - Выводит измененный массив на экран.


In [4]:
n = int(input('Input num of array: '))
my_list = [rd.randint(0, 100) for i in range(n)]
my_array = np.array(my_list)
print(my_array)
x = int(input('Input number for multiplication: '))
print(x * my_array)


Input num of array:  4


[77 61  0 36]


Input number for multiplication:  2


[154 122   0  72]
