In [ ]:
1. Сравнение производительности операций над массивами:


Напишите программу, которая:

- Генерирует два больших одномерных массива с 1 миллионом элементов каждый, заполненных случайными числами.

- Сначала выполняет поэлементное сложение этих массивов, используя циклы Python.

- Затем выполняет ту же операцию, используя возможности NumPy.

- Измеряет и выводит время выполнения каждого подхода.


Пример вывода:


Время выполнения сложения с использованием цикла Python: 0.5 секунды.

Время выполнения сложения с использованием NumPy: 0.01 секунды.

In [2]:
import numpy as np
import timeit

In [17]:
arr_1 = np.arange(1000000)
arr_2 = np.arange(1000000)
result = %timeit -o -q [i + j for i, j in zip(arr_1, arr_2)]
print(f'Время выполнения сложения с использованием цикла Python: {result}.')

Время выполнения сложения с использованием цикла Python: 185 ms ± 8.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each).


In [21]:
arr_1 = np.arange(1000000)
arr_2 = np.arange(1000000)
result = %timeit -o -q arr_1 + arr_2
print(f'Время выполнения сложения с использованием NumPy: {result}.')

Время выполнения сложения с использованием NumPy: 3.62 ms ± 231 μs per loop (mean ± std. dev. of 7 runs, 100 loops each).


In [ ]:
2. Анализ расположения данных в памяти:

Создать большой двумерный массив и исследовать, как изменение порядка (C-style и Fortran-style) влияет на производительность операций сложения и умножения.

Можно использовать тот же бенчмарк что и в лекции. Необходимо погуглить про то, как завести массив с порядком в Fortran-style. Не забывайте про magic в jupyter.

In [4]:
arr_c_1 = np.random.randint(0, 1000000, (1000, 1000))
arr_c_2 = np.random.randint(0, 1000000, (1000, 1000))
print(arr_c_1) 
print(arr_c_2)

[[293800 741133 209408 ... 580669 134932 275091]
 [804441 958688 167990 ... 856246 889608 228480]
 [742005 202946 719012 ... 488614 850029 546254]
 ...
 [133571  22735 303932 ... 885807 975585 199504]
 [ 31930 712540 959038 ...  14982 722487 527222]
 [182049 504214 382595 ... 164536 229584 305370]]
[[660751 403756 317700 ... 625758 555902 144000]
 [ 46000 278674  27498 ... 202587 227079  72567]
 [ 51045  90877  13609 ... 328558 414650 131284]
 ...
 [655283 926667 684202 ... 622289 302952 439923]
 [195947 795069 722060 ... 974591 912894 844489]
 [912043 749367 815094 ... 512903 204204  23059]]


In [5]:
%%timeit

multi_c = arr_c_1 * arr_c_2
multi_c

2.43 ms ± 770 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%%timeit

sum_c = arr_c_1 + arr_c_2
sum_c

2.03 ms ± 129 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
arr_1 = np.random.randint(0, 1000000, (1000, 1000))
arr_f_1 = np.array(arr_1, order = 'F')
arr_2 = np.random.randint(0, 1000000, (1000, 1000))
arr_f_2 = np.array(arr_2, order = 'F')
print(arr_f_1)
print(arr_f_2)

[[939777 779258 295924 ... 810320 224289 281975]
 [666883 744122 863195 ... 738894 310952 230870]
 [413718 674378 312546 ... 258676 595229 610709]
 ...
 [696336 402328 835560 ... 945654 527831 317042]
 [240316  94885 159121 ...  80314 536691 802277]
 [483155 341327  40563 ... 838298 454195 654093]]
[[432466 662972 554329 ... 734260 231065 178858]
 [741996 944551 757018 ... 575789 866488 217681]
 [ 62944  30487 544359 ... 414936 373664 617729]
 ...
 [572234 588122 263835 ... 539199 773896 604071]
 [268380 476147  10346 ... 521446 109099 309415]
 [883529 262442  43064 ... 994070 928326 575938]]


In [9]:
%%timeit

multi_f = arr_f_1 * arr_f_2
multi_f

2.58 ms ± 598 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%%timeit

sum_f = arr_f_1 + arr_f_2
sum_f

2 ms ± 70.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
3. Обратная матрица и определитель:


Напишите программу, которая:

- Запрашивает у пользователя размер квадратной матрицы N.

- Генерирует квадратную матрицу размером N x N, заполненную случайными числами от -10 до 10.

- Выводит сгенерированную матрицу на экран.

- Вычисляет и выводит определитель матрицы.

- Если определитель не равен нулю, программа должна вычислить и вывести обратную матрицу. 
В противном случае, программа должна сообщить, что обратной матрицы не существует.



In [3]:
N = int(input('Input size of matrix: '))
mat = np.random.randint(-10, 10, (N, N))
print(f'Generated matrix:\n {mat}')
det = np.linalg.det(mat)
print(f'Matrix determinant: {det:.0f}')
if det != 0:
    print(f'Inverse matrix:\n {np.linalg.inv(mat)}')
else:
    print('Inverse matrix isn\'t exist')

Input size of matrix:  4


Generated matrix:
 [[-9 -8 -8 -2]
 [ 8  6 -7  3]
 [ 4  0  0 -6]
 [ 8 -2  9  4]]
Matrix determinant: 9456
Inverse matrix:
 [[ 0.02538071  0.05583756  0.06345178  0.06598985]
 [-0.10448393 -0.00486464 -0.03204315 -0.09665821]
 [-0.05329949 -0.06725888 -0.00824873  0.01142132]
 [ 0.01692047  0.03722504 -0.12436548  0.04399323]]
