In [ ]:
1. Индексация массивов NumPy:

Напишите программу, которая:

- Запрашивает у пользователя ввод одномерного массива, элементы которого вводятся в виде чисел, разделенных пробелами.

- Преобразует введенную строку в массив NumPy.

- Запрашивает у пользователя индекс элемента, который необходимо извлечь из массива.

- Выводит значение элемента по запрошенному индексу.

- Запрашивает у пользователя ввод диапазона индексов в формате `начало:конец`, чтобы извлечь срез массива.

- Выводит срез массива.


In [63]:
import numpy as np

nums = list(map(int, input('Enter numbers with spaces').split()))
arr = np.array(nums)
print(arr)
element = int(input('Enter element number for extracting:'))
print(arr[element])
slice_1, slice_2 = map(int, input('Enter the first index range for slicing: ').split(':'))
print(f'Срез массива: {arr[slice_1:slice_2]}')


Enter numbers with spaces 1 2 3 4 5 6 7 8 9


[1 2 3 4 5 6 7 8 9]


Enter element number for extracting: 2


3


Enter the first index range for slicing:  4:7


Срез массива: [5 6 7]


In [ ]:
2. Операции с матрицами в NumPy:

Напишите программу, которая:

- Запрашивает у пользователя размеры матрицы MxN.

- Генерирует две матрицы указанных размеров, заполненные случайными числами от 0 до 9.

- Выводит обе сгенерированные матрицы на экран.

- Выполняет и выводит результат одной из следующих операций (на выбор пользователя): сложение матриц, умножение матриц, транспонирование одной из матриц.

- Если выбрано умножение, убедитесь, что размеры матриц соответствуют правилам матричного умножения.

In [66]:
import random as rd

M, N = map(int, input('Enter matrix size: ').split('x'))
mat_1 = np.array([[rd.randint(0, 9) for i in range(N)] for i in range(M)])
mat_2 = np.array([[rd.randint(0, 9) for i in range(N)] for i in range(M)])
print(mat_1)
print(mat_2)
addition = mat_1 + mat_2
multiplication = mat_1 * mat_2
transposition_1 = f'{mat_1.T}'
transposition_2 = f' {mat_2.T}'


while True:
    operation = input('Select operation for matrix (addition, multiplication, transposition). For exit enter \'q\': ')
    
    if operation == 'addition':
        print(addition)
    elif operation == 'multiplication':
        print(multiplication)
    elif operation == 'transposition':
        T_mat = input('What matrix should be transposed 1 or 2?')
        if T_mat == '1':
            print(transposition_1)
        elif T_mat == '2':
            print(transposition_2)
        else:
            print('Enter correct number of matrix!')
    elif operation == 'q':
        break    
    else:
        print('Please enter correct name of operation from list!')

Enter matrix size:  4x5


[[2 7 2 9 3]
 [2 5 4 7 1]
 [6 7 1 0 9]
 [6 5 4 1 9]]
[[1 0 2 7 7]
 [1 6 9 2 3]
 [9 8 3 3 1]
 [4 8 6 2 3]]


Select operation for matrix (addition, multiplication, transposition). For exit enter 'q':  addition


[[ 3  7  4 16 10]
 [ 3 11 13  9  4]
 [15 15  4  3 10]
 [10 13 10  3 12]]


Select operation for matrix (addition, multiplication, transposition). For exit enter 'q':  multiplication


[[ 2  0  4 63 21]
 [ 2 30 36 14  3]
 [54 56  3  0  9]
 [24 40 24  2 27]]


Select operation for matrix (addition, multiplication, transposition). For exit enter 'q':  transposition
What matrix should be transposed (1 or 2? 1


[[2 2 6 6]
 [7 5 7 5]
 [2 4 1 4]
 [9 7 0 1]
 [3 1 9 9]]


Select operation for matrix (addition, multiplication, transposition). For exit enter 'q':  q
