In [ ]:
1. Индексация массивов NumPy:

Напишите программу, которая:

- Запрашивает у пользователя ввод одномерного массива, элементы которого вводятся в виде чисел, разделенных пробелами.

- Преобразует введенную строку в массив NumPy.

- Запрашивает у пользователя индекс элемента, который необходимо извлечь из массива.

- Выводит значение элемента по запрошенному индексу.

- Запрашивает у пользователя ввод диапазона индексов в формате `начало:конец`, чтобы извлечь срез массива.

- Выводит срез массива.


In [16]:
import numpy as np

nums = list(map(int, input('Enter numbers with spaces').split()))
arr = np.array(nums)
print(arr)
element = int(input('Enter element number for extracting:'))
print(arr[element])
slices_1 = int(input('Enter the first index range for slicing: '))
slices_2 = int(input('Enter the second index range for slicing: '))
print(arr[slices_1:slices_2])


Enter numbers with spaces 1 2 3 4 5 6


[1 2 3 4 5 6]


Enter element number for extracting: 2


3


Enter the first index range for slicing:  1
Enter the second index range for slicing:  4


[2 3 4]


In [ ]:
2. Операции с матрицами в NumPy:

Напишите программу, которая:

- Запрашивает у пользователя размеры матрицы MxN.

- Генерирует две матрицы указанных размеров, заполненные случайными числами от 0 до 9.

- Выводит обе сгенерированные матрицы на экран.

- Выполняет и выводит результат одной из следующих операций (на выбор пользователя): сложение матриц, умножение матриц, транспонирование одной из матриц.

- Если выбрано умножение, убедитесь, что размеры матриц соответствуют правилам матричного умножения.

In [52]:
import random as rd

M, N = map(int, input('Enter matrix size: ').split('x'))
mat_1 = np.array([[rd.randint(0, 9) for i in range(N)] for i in range(M)])
mat_2 = np.array([[rd.randint(0, 9) for i in range(N)] for i in range(M)])
print(mat_1)
print(mat_2)
addition = mat_1 + mat_2
multiplication = mat_1 * mat_2
transposition = f'{mat_1.T} \n {mat_2.T}'


while True:
    operation = input('Select operation for matrix (addition, multiplication, transposition). For exit enter \'q\': ')
    
    if operation == 'addition':
        print(addition)
    elif operation == 'multiplication':
        print(multiplication)
    elif operation == 'transposition':
        print(transposition)
    elif operation == 'q':
        break    
    else:
        print('Please enter correct name of operation from list!')

Enter matrix size:  2x3


[[3 1 5]
 [3 2 6]]
[[9 0 7]
 [4 7 3]]


Select operation for matrix (addition, multiplication, transposition). For exit enter 'q':  addition


[[12  1 12]
 [ 7  9  9]]


Select operation for matrix (addition, multiplication, transposition). For exit enter 'q':  multiplication


[[27  0 35]
 [12 14 18]]


Select operation for matrix (addition, multiplication, transposition). For exit enter 'q':  transposition


[[3 3]
 [1 2]
 [5 6]] 
 [[9 4]
 [0 7]
 [7 3]]


Select operation for matrix (addition, multiplication, transposition). For exit enter 'q':  q
