In [ ]:
1. Сравнение производительности операций над массивами:


Напишите программу, которая:

- Генерирует два больших одномерных массива с 1 миллионом элементов каждый, заполненных случайными числами.

- Сначала выполняет поэлементное сложение этих массивов, используя циклы Python.

- Затем выполняет ту же операцию, используя возможности NumPy.

- Измеряет и выводит время выполнения каждого подхода.


Пример вывода:


Время выполнения сложения с использованием цикла Python: 0.5 секунды.

Время выполнения сложения с использованием NumPy: 0.01 секунды.

In [10]:
import numpy as np
import timeit

In [17]:
arr_1 = np.arange(1000000)
arr_2 = np.arange(1000000)
result = %timeit -o -q [i + j for i, j in zip(arr_1, arr_2)]
print(f'Время выполнения сложения с использованием цикла Python: {result}.')

Время выполнения сложения с использованием цикла Python: 185 ms ± 8.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each).


In [21]:
arr_1 = np.arange(1000000)
arr_2 = np.arange(1000000)
result = %timeit -o -q arr_1 + arr_2
print(f'Время выполнения сложения с использованием NumPy: {result}.')

Время выполнения сложения с использованием NumPy: 3.62 ms ± 231 μs per loop (mean ± std. dev. of 7 runs, 100 loops each).


In [ ]:
2. Анализ расположения данных в памяти:

Создать большой двумерный массив и исследовать, как изменение порядка (C-style и Fortran-style) влияет на производительность операций сложения и умножения.

Можно использовать тот же бенчмарк что и в лекции. Необходимо погуглить про то, как завести массив с порядком в Fortran-style. Не забывайте про magic в jupyter.

In [45]:
arr_c_1 = np.random.randint(0, 1000000, (1000, 1000))
arr_c_2 = np.random.randint(0, 1000000, (1000, 1000))
print(arr_c_1) 
print(arr_c_2)

[[540536 928141 749721 ... 367992  42192 912445]
 [156671 725124 960327 ... 661867 683656 534723]
 [553144 158236 963023 ... 139544 877384 780394]
 ...
 [822264 627316 953863 ... 288383 838855 925189]
 [196925 264415 713453 ...  82861 690437 966410]
 [926631 132007 454197 ... 292505  34838 993836]]
[[459384 942618 682284 ... 978782 858121 511749]
 [901960 463097 339975 ...  91513 686862 358856]
 [663227 694619 111642 ... 578176 121559 670908]
 ...
 [503985 387072 859787 ... 382531 978624 145936]
 [966491  10054 788535 ... 563961 849154 597699]
 [479668 160099 443982 ...  53766 406239 617855]]


In [46]:
%%timeit

multi_c = arr_c_1 * arr_c_2
multi_c

2.32 ms ± 72 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [47]:
%%timeit

sum_c = arr_c_1 + arr_c_2
sum_c

2.11 ms ± 221 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [49]:
arr_f_1 = np.random.randint(0, 1000000, (1000, 1000))
arr_f_1 = np.array(arr, order = 'F')
arr_f_2 = np.random.randint(0, 1000000, (1000, 1000))
arr_f_2 = np.array(arr, order = 'F')
print(arr_f_1)
print(arr_f_2)

[[29 99 67 ... 40 23 96]
 [18 17 73 ...  9 63 71]
 [30 76 92 ... 63  4 15]
 ...
 [89 18 99 ... 22 80 26]
 [73 18  6 ... 51 94 23]
 [80 35 15 ... 68 18 78]]
[[29 99 67 ... 40 23 96]
 [18 17 73 ...  9 63 71]
 [30 76 92 ... 63  4 15]
 ...
 [89 18 99 ... 22 80 26]
 [73 18  6 ... 51 94 23]
 [80 35 15 ... 68 18 78]]


In [50]:
%%timeit

multi_f = arr_f_1 * arr_f_2
multi_f

11.1 μs ± 339 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [51]:
%%timeit

sum_f = arr_f_1 + arr_f_2
sum_f

8.51 μs ± 211 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
3. Обратная матрица и определитель:


Напишите программу, которая:

- Запрашивает у пользователя размер квадратной матрицы N.

- Генерирует квадратную матрицу размером N x N, заполненную случайными числами от -10 до 10.

- Выводит сгенерированную матрицу на экран.

- Вычисляет и выводит определитель матрицы.

- Если определитель не равен нулю, программа должна вычислить и вывести обратную матрицу. 
В противном случае, программа должна сообщить, что обратной матрицы не существует.



In [71]:
N = int(input('Input size of matrix: '))
mat = np.random.randint(-10, 10, (N, N))
print(f'Generated matrix:\n {mat}')
det = np.linalg.det(mat)
print(f'Matrix determinant: {det:.0f}')
if det != 0:
    print(f'Inverse matrix:\n {np.linalg.inv(mat)}')
else:
    print('Inverse matrix isn\'t exist')

Input size of matrix:  4


Generated matrix:
 [[  6  -3 -10  -2]
 [  3   6  -5  -1]
 [ -9   8 -10   6]
 [  2   8   5   2]]
Matrix determinant: -4125
Inverse matrix:
 [[ 1.40606061e-01 -9.93939394e-02 -1.81818182e-02  1.45454545e-01]
 [-6.66666667e-02  1.33333333e-01 -8.51591525e-18 -1.27738729e-17]
 [-4.16969697e-02 -2.56969697e-02 -2.90909091e-02  3.27272727e-02]
 [ 2.30303030e-01 -3.69696970e-01  9.09090909e-02  2.72727273e-01]]
