In [3]:
import numpy as np

In [2]:
 #одномерный массив
one_d_array = np.array([1,2,3])

In [3]:
two_d_array = np.array([[1,2,3], [4,5,6]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
list_2d = [[1,2],[3,4]]
two_d_array = np.array(list_2d)
display(two_d_array)

array([[1, 2],
       [3, 4]])

In [ ]:
Данные, заисанные в строчку - одномерный массив (вектор), имеет одно измерение
list = [1,2,3,4]

In [7]:
list_2d = [[1],[2],[3],[4]] # вектор-столбец, имеет 2 измерения (таблица)
two_d_array = np.array(list_2d)
two_d_array

array([[1],
       [2],
       [3],
       [4]])

In [4]:
col = np.array([[10], [20]])
print(col)

[[10]
 [20]]


In [11]:
ones_array = np.ones((3, 4)) # 3 строки, 4 столбца - размер массива
print(ones_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
zeros_array = np.zeros_like(ones_array)
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a = np.arange(0, 9, 2) # 3 параметра - начало, конец и шаг
print(a)
b = np.arange(0., 8, 2)
print(b)


[0 2 4 6 8]
[0. 2. 4. 6.]


In [14]:
a = np.arange(10) # выводит просто целые числа от 0 до 10
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a = np.linspace(0, 8, 7) # есть отрезок от 0 до 8, нужно поделить его 
#на равные кусочки так, чтобы отмеченных точек было 7 штук. т.е. 5 точек внутри и 2 точки по краям
print(a)


[0.         1.33333333 2.66666667 4.         5.33333333 6.66666667
 8.        ]


In [16]:
a = np.linspace(0, 8, 9)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [17]:
a = np.linspace(0, 8, 3)
print(a)

[0. 4. 8.]


In [20]:
# Создайте и выведите последовательность чисел от 10 до 20 
# с постоянным шагом, длина последовательности – 21. Скажите сначала устно, какой должен быть ответ.
a = np.linspace(10, 20, 21)
print(a)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20. ]


In [5]:
# Трехмерный массив
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
three_d_array.ndim #показывает размерность

3

In [6]:
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
three_d_array[0, 1, 0]
#[[1,2],[3,4]]
#[3,4]
#3
#размерность - это сколько нам нужно написать индексов, чтобы добраться до объекта (кол-во элементов кортежа)

np.int64(3)

In [7]:
# Трехмерный массив
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
three_d_array.shape # описывает сколько длина в каждой размерности, самая полная информация (длина, ширина и т.д), это кортеж

(2, 2, 2)

In [17]:
ones_array = np.ones((3, 4))
zeros_array = np.zeros_like(ones_array)
zeros_array.shape

(3, 4)

In [12]:
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
len(three_d_array) #показывает количество строк (первый элемент кортежа shape)

2

In [13]:
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
three_d_array.size #показывает произведение всех элементов shape (кортежа)

8

In [ ]:
# ndim, shape, len, size
# shape -- кортеж
# ndim -- кол-во элементов shape
# len -- первый элемент shape
# size -- произведение всех элементов shape

In [19]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
array.shape

(4, 3)

In [ ]:
Под каждый элемент выделено фиксированное кол-во памяти.
Все элементы в массиве имеют одинаковый тип !

In [20]:
# Массив вещественных чисел
two_d_array = np.array([[1, 2, 3.1], [4, 5, 6]])
two_d_array #если есть веществ.число в массиве, то все числа становятся вещественными

array([[1. , 2. , 3.1],
       [4. , 5. , 6. ]])

In [21]:
# массив строк
two_d_array = np.array([[1, 2, 3], ["A", "B", "C"]])
two_d_array

array([['1', '2', '3'],
       ['A', 'B', 'C']], dtype='<U21')

In [22]:
two_d_array = np.array([[1, 2, 3], ["A", "B", "C"*28]])
two_d_array


array([['1', '2', '3'],
       ['A', 'B', 'CCCCCCCCCCCCCCCCCCCCCCCCCCCC']], dtype='<U28')

In [24]:
# сколько памяти занимает объект
print(np.array([1, 2, 3]).itemsize)
print(np.array([[1, 2, 3], ["A", "B", "C"]]).itemsize)
#8 - значит 8 байт выделяется под целое число (1 элмент), это тип массива "целые числа"
# под вещественные числа выделяется 8 байт
# 44 == 11 * 4, потому что '<U11' означает не более 11 символов Unicode, каждый из которых кодируется не более чем 4 байтами.

8
84


In [25]:
a = np.array([[1, 2, 3], ["A", "B", "C"]])
print(a)
a[0][0] = "a"*10+"b"*10
a


[['1' '2' '3']
 ['A' 'B' 'C']]


array([['aaaaaaaaaabbbbbbbbbb', '2', '3'],
       ['A', 'B', 'C']], dtype='<U21')

In [26]:
a = np.array([[1, 2, 3], ["A", "B", "C"]])
a[0][0] = "a"*20+"b"*10 #не поместятся все символы, т.к. 21 только поместится
a

array([['aaaaaaaaaaaaaaaaaaaab', '2', '3'],
       ['A', 'B', 'C']], dtype='<U21')

In [27]:
При создании матрицы пайтон выделяется память, где под каждый элемент выделяется не больше 21 байт (юникодная строка)

SyntaxError: invalid syntax (1186922273.py, line 1)

In [28]:
#Список. Здась храним, что хотим в отличие от массива
list_int_str = [[1, 2, 3], ["A", "B", "C"]]
print(list_int_str)
list_int_float = [[1, 2, 3.0], [4, 5, 6]]
print(list_int_float)


[[1, 2, 3], ['A', 'B', 'C']]
[[1, 2, 3.0], [4, 5, 6]]


In [29]:
#превращает массив в список
two_d_array.tolist()


[['1', '2', '3'], ['A', 'B', 'CCCCCCCCCCCCCCCCCCCCCCCCCCCC']]

In [31]:
# Массив с определенным типом данных, задаем тип для каждого элемента массива float
float_array = np.array([1, 2, 3], dtype=np.float64)
float_array

array([1., 2., 3.])

In [32]:
# опросить тип данных
float_array = np.array([1, 2, 3], dtype=np.float64)
print(float_array.dtype) 

float64


In [ ]:
Менять тип данных уже созданного массива - дорогая операция для времени и памяти!

In [33]:
#astype — это метод, который позволяет поменять тип уже существующего массива.
int_array = np.array([1, 2, 3], dtype=np.int8)
print(int_array.astype(np.float32))

[1. 2. 3.]


In [34]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1] + arr[3])


6


In [35]:
arr = np.array([1.0, 2, 3])
print(arr.dtype)


float64


In [36]:
arr = np.arange(5, 15, 2)
print(arr)

[ 5  7  9 11 13]


In [ ]:
Создайте одномерный массив из случайных чисел. Выведите его тип, размер и содержимое.

In [37]:
import random as rd

In [39]:
my_list = [rd.uniform(0, 1) for i in range(10)]
my_list

[0.7852768367953908,
 0.01838433277286111,
 0.5446391460403496,
 0.6671560712293132,
 0.441896019911457,
 0.6746371797965551,
 0.5877762928875282,
 0.28735288917982893,
 0.03814478852225345,
 0.15969721079727472]

In [41]:
my_array = np.array(my_list)
my_array

array([0.78527684, 0.01838433, 0.54463915, 0.66715607, 0.44189602,
       0.67463718, 0.58777629, 0.28735289, 0.03814479, 0.15969721])

In [42]:
my_array.dtype

dtype('float64')

In [43]:
my_array.size

10

In [44]:
print(my_array)

[0.78527684 0.01838433 0.54463915 0.66715607 0.44189602 0.67463718
 0.58777629 0.28735289 0.03814479 0.15969721]


In [ ]:
Создайте массив размером 3x4, полностью заполненный единицами, и выведите его.

In [47]:
a_ones = np.ones((3,4))
a_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
Используя функцию np.arange, создайте массив чисел от 0 до 10 с шагом 2. Затем
создайте массив с теми же числами, используя np.linspace, и сравните результаты.

In [52]:
a = np.arange(0.,11,2)
a

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [51]:
a = np.linspace(0, 10, 6)
a

array([ 0.,  2.,  4.,  6.,  8., 10.])