In [2]:
two_d_list = [[1, 2, 3], [4, 5, 6]]
# Сложение списков
print(two_d_list + two_d_list)
# Умножение списка на число
print(two_d_list * 2)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [6]:
import numpy as np
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
# Сложение массивов
print(two_d_array + two_d_array)
# Умножение массивов. Когда умножаем на один и тот же массив, то по сути возводим в квадрат каждый элемент
print(two_d_array * two_d_array)
# Умножение массива на число – каждое число в массиве умножится на это число
print(two_d_array * 5)

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[ 5 10 15]
 [20 25 30]]


In [7]:
square = np.array([[1, 2], [4, 5]])
two_d_array + square
# не получится сложить,т.к. разные размеры массивов. Определяем параметр shape, он должен быть одинаковым

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [8]:
square = np.array([[1, 2, 8], [4, 5, 9]])
two_d_array + square

array([[ 2,  4, 11],
       [ 8, 10, 15]])

In [9]:
square = np.array([[1, 2, 8], [4, 5, 9]])
two_d_array < square

array([[False, False,  True],
       [False, False,  True]])

In [11]:
square = np.array([[1, 2, 8], [4, 5, 9]])
bool_ar = two_d_array < square
bool_ar
#массивы работают поэлементно!

array([[False, False,  True],
       [False, False,  True]])

In [13]:
square = np.array([[1, 2, 8], [4, 5, 9]])
np.any(two_d_array > square)

np.False_

In [14]:
#Расширение размерности
one_d_array = np.array([10, 20, 30])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(one_d_array + two_d_array)


[[11 22 33]
 [14 25 36]]


In [15]:
one_d_array = np.array([10, 20, 30, 40])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(one_d_array + two_d_array)
#так не получится растянуть

ValueError: operands could not be broadcast together with shapes (4,) (2,3) 

In [16]:
col = np.array([[10], [20]])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(col + two_d_array)

[[11 12 13]
 [24 25 26]]


In [17]:
col = np.array([1, 2])
two_d_array = np.array([3, 4, 5])
print(np.concatenate( [col, two_d_array] )) # скеливает массивы

[1 2 3 4 5]


In [ ]:
col = np.array([[10], [20], [30]]) #здесь это вектор-столбец. Если все элементы в одну строку, то будет без квадратных скобок и будет просто вектор
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(col + two_d_array)
#разные размеры, не получится сложить

In [18]:
mult = np.array([[10, 20, 30]]) # здесь просто вектор, его можно растянуть (1 строка и 3 элемента)
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(mult * two_d_array)

[[ 10  40  90]
 [ 40 100 180]]


In [19]:
a = np.array([0, 2, 1])
b = np.array([3, 4, 5])
print(a - b) # [-3 -2 -4]
print(a / b) # [0. 0.5 0.2]
print(a ** 2) # [0 4 1]
print(a ** b) # [0 16 1]

[-3 -2 -4]
[0.  0.5 0.2]
[0 4 1]
[ 0 16  1]


In [20]:
print(b / a) # [inf 2. 5.]


[inf  2.  5.]


C:\Users\user\AppData\Local\Temp\ipykernel_22008\756128656.py:1: RuntimeWarning: divide by zero encountered in divide
  print(b / a) # [inf 2. 5.]


In [21]:
b = np.array([3, 4, 5])
print(type((b / 0)[0]))


<class 'numpy.float64'>


C:\Users\user\AppData\Local\Temp\ipykernel_22008\73444277.py:1: RuntimeWarning: divide by zero encountered in divide
  print(type((b / 0)[0]))


In [22]:
assert np.inf == (b / 0)[0]

C:\Users\user\AppData\Local\Temp\ipykernel_22008\3780871145.py:1: RuntimeWarning: divide by zero encountered in divide
  assert np.inf == (b / 0)[0]


In [24]:
assert 1 == 0

AssertionError: 

In [26]:
print(np.array([1])/0)
print(np.array([1])/-0.)


[inf]
[-inf]


C:\Users\user\AppData\Local\Temp\ipykernel_22008\835973647.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([1])/0)
C:\Users\user\AppData\Local\Temp\ipykernel_22008\835973647.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.array([1])/-0.)


In [27]:
np.inf + np.inf

inf

In [28]:
2 * np.inf

inf

In [29]:
-2 * np.inf

-inf

In [30]:
np.inf - np.inf # nan - это действительное число, float64

nan

In [31]:
np.inf * 0

nan

In [36]:
print(np.array([np.inf])/0)
# [inf]
print(np.inf / 0.)
# ZeroDivisionError: float division by zero
print(0 / np.inf)
# 0.0
print(np.nan + 1, np.inf + 1, np.inf * 0, 1. / np.inf)
# nan inf nan 0.0

[inf]


ZeroDivisionError: float division by zero

In [37]:
a = np.array([0, 2, 1])
print(np.sin, type(np.sin))
print(np.sin(a))


<ufunc 'sin'> <class 'numpy.ufunc'>
[0.         0.90929743 0.84147098]


In [38]:
a = np.array([0, 2, 1])
b = np.array([3, 2, 5])
print(a > b)

print(a == b)

c = a >= 2
print(c)


[False False False]
[False  True False]
[False  True False]


In [ ]:
np.any — это аналог any и all из классического Python, возвращает
True, если хотя бы один элемент в массиве True, np.all –
если все элементы в массиве True.

In [39]:
print(np.any(c), np.all(c))

True False


In [40]:
b *= 2
print(b)

[ 6  4 10]


In [41]:
d = np.array([1, 5, 6])
print(d.sum(), d.prod(), d.max(), d.min(), d.mean(), d.std()) #mean-среднее, std - среднее квадратичное

12 30 6 1 4.0 2.160246899469287


In [42]:
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b))
print(np.sin(b))
print(np.e, np.pi)


[2.44948974 2.         3.16227766]
[  403.42879349    54.59815003 22026.46579481]
[1.79175947 1.38629436 2.30258509]
[-0.2794155  -0.7568025  -0.54402111]
2.718281828459045 3.141592653589793


In [ ]:
Массив частичных сумм (cumsum()) — это массив, на первом месте которого стоит первый
элемент, на втором – сумма первого и второго, на третьем
– сумма первого, второго и третьего и т.д.

In [43]:
print(b.cumsum())

[ 6 10 20]


In [44]:
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube * cube)


[[[ 1  4]
  [ 9 16]]

 [[25 36]
  [49 64]]]


In [45]:
print(cube + np.array([[10, 20], [30, 40]]))

[[[11 22]
  [33 44]]

 [[15 26]
  [37 48]]]


In [46]:
print(cube + np.array([[10, 20]])) #размерность (1,2)

[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


In [47]:
print(cube + np.array([10, 20])) #размерность 1

[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


In [48]:
print(cube + np.array([[10], [20]]))

[[[11 12]
  [23 24]]

 [[15 16]
  [27 28]]]


In [49]:
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
cube

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
Создайте массив из 20 чисел от −2𝜋 до 2𝜋.


In [53]:
a = np.linspace([-2 * np.pi],[2 * np.pi], 20)
a

array([[-6.28318531],
       [-5.62179738],
       [-4.96040945],
       [-4.29902153],
       [-3.6376336 ],
       [-2.97624567],
       [-2.31485774],
       [-1.65346982],
       [-0.99208189],
       [-0.33069396],
       [ 0.33069396],
       [ 0.99208189],
       [ 1.65346982],
       [ 2.31485774],
       [ 2.97624567],
       [ 3.6376336 ],
       [ 4.29902153],
       [ 4.96040945],
       [ 5.62179738],
       [ 6.28318531]])

In [ ]:
Посчитайте поэлементные квадраты косинусов для данного массива.


In [55]:
a = np.linspace([-2 * np.pi],[2 * np.pi], 20)
np.cos(a) ** 2

array([[1.        ],
       [0.62274274],
       [0.06026312],
       [0.16135921],
       [0.77347408],
       [0.97290862],
       [0.45871033],
       [0.00681935],
       [0.29915229],
       [0.89457025],
       [0.89457025],
       [0.29915229],
       [0.00681935],
       [0.45871033],
       [0.97290862],
       [0.77347408],
       [0.16135921],
       [0.06026312],
       [0.62274274],
       [1.        ]])

In [ ]:
С помощью np.all проверьте, что в ответе только числа не больше единицы.

In [58]:
np.all(np.cos(a)**2 <= 1)

np.True_

In [ ]:
'''
1. Создайте массив из 20 чисел от 2𝜋 до 2𝜋.
Посчитайте поэлементные квадраты косинусов для данного массива.
С помощью np.all проверьте, что в ответе только числа не больше единицы.
'''
a = np.linspace(-2*np.pi, 2*np.pi, 20)
print(a)
print('------')
print(np.cos(a)**2)
print('------')
print(np.all(np.cos(a)**2 <= 1))