In [ ]:
Создайте массив 4x4 со значениями от 0 до 15. Выведите:
Умножьте исходный массив на его третью строку
Вычтите из исходного массива второй столбец

In [2]:
import numpy as np

a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
b = a * a[2]
b

array([[  0,   9,  20,  33],
       [ 32,  45,  60,  77],
       [ 64,  81, 100, 121],
       [ 96, 117, 140, 165]])

In [4]:
c = a - a[:, 1]
c

array([[ -1,  -4,  -7, -10],
       [  3,   0,  -3,  -6],
       [  7,   4,   1,  -2],
       [ 11,   8,   5,   2]])

In [ ]:
1. Напишите программу, которая:
a. Запрашивает у пользователя ввод двух списков – в первом 5
элементов, во втором 4. Списки вводятся в виде чисел, разделенных
пробелами.
b. Объединяет введенные списки в один новый список из 9 элементов.
c. Преобразует полученный список в массив NumPy.
d. Вычисляет минимальное, среднее и максимальное значение для
полученного массива.


In [10]:
lst_1 = list(map(int, input('Input 5 elements').split()))
lst_2 = list(map(int, input('Input 4 elements').split()))

joined_lst = lst_1 + lst_2
array_lst = np.array(joined_lst)
print(array_lst.min(), array_lst.mean(), array_lst.max())


Input 5 elements 1 2 3 4 5
Input 4 elements 6 7 8 9


1 5.0 9


In [ ]:
2. С помощью функции np.linspace создайте массив из 9 элементов со
значениями между средним и максимальным из предыдущей задачи. Найдите
поэлементную сумму массивов из первой и второй задачи.

In [14]:
lin_array = np.linspace(5.0, 9, 9)
print(lin_array)
print(array_lst + lin_array)

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9. ]
[ 6.   7.5  9.  10.5 12.  13.5 15.  16.5 18. ]


In [ ]:
# 2 вариант
list_one = list(map(int, input("enter 5 elements: ").split()))
list_two = list(map(int, input("enter 4 elements: ").split()))
new_list = list_one + list_two
print(new_list)
new_arr = np.array(new_list)
print(new_arr)
max_arr = np.max(new_arr)
#print(np.min(new_arr))
avg_arr = np.average(new_arr)
print(max_arr, avg_arr)
arr_new = np.linspace(avg_arr, max_arr, 9)
total_arr = arr_new + new_arr
print(arr_new)
print(total_arr)

In [ ]:
3. Создайте массив из десяти элементов 1, 2, …, 10. С помощью функции cumprod
вычислите кумулятивные произведения элементов этого массива.

In [ ]:
new_array = np.arrange(1, 11)
cumprod_array = np.cumprod(new_array)

In [ ]:
4. Напишите программу, которая:
a. Запрашивает у пользователя ввод трех списков, каждый из трех
элементов. Списки вводятся в виде чисел, разделенных пробелами.
b. Создает список из полученных списков.
c. Преобразует полученный двумерный список в двумерный массив
NumPy (назовем его матрицей А.
d. Вычисляет среднее значение для полученного массива.


In [15]:
list_one = list(map(int, input("enter 3 elements: ").split()))
list_two = list(map(int, input("enter 3 elements: ").split()))
list_three = list(map(int, input("enter 3 elements: ").split()))
total_lst = [list_one, list_two, list_three]

A = np.array(total_lst)
avg_A = np.mean(A)
avg_A

enter 3 elements:  1 2 3
enter 3 elements:  4 5 6
enter 3 elements:  7 8 9


np.float64(5.0)

In [ ]:
5. Продолжите предыдущую программу. Далее она:
a. Создает матрицу такого же размера, но заполненную вычисленным
средним значением (назовем ее матрицей B.
b. Разделите матрицу A на матрицу B - это будет матрица С.
c. Создайте новую матрицу, заполненную логическими значениями – True,
если элемент матрицы С больше 1, False – если меньше 1.


In [17]:
B = np.full_like(A, avg_A)

C = A / B
print(C)
new_matrix = (C > 1)
print(new_matrix)

[[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]]
[[False False False]
 [False False  True]
 [ True  True  True]]


In [ ]:
6. Продолжите предыдущую программу. Далее она:
a. Объединяет матрицы A и B в две новые матрицы – одну размера 3х6,
другую – 6х3.
b. Запрашивает у пользователя два числа - x и y.
c. Первую матрицу умножает на x, из второй вычитает y.


In [24]:
three_six = np.concatenate((A, B), axis = 0) #по вертикали
six_three = np.concatenate((A, B), axis = 1) #по горизонтали
print(three_six)
print(six_three)


[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
[[1 2 3 5 5 5]
 [4 5 6 5 5 5]
 [7 8 9 5 5 5]]


In [25]:
x = 6
y = 7
print(three_six * x)
print(six_three - y)

[[ 6 12 18]
 [24 30 36]
 [42 48 54]
 [30 30 30]
 [30 30 30]
 [30 30 30]]
[[-6 -5 -4 -2 -2 -2]
 [-3 -2 -1 -2 -2 -2]
 [ 0  1  2 -2 -2 -2]]


In [ ]:
7. Напишите программу, которая запрашивает у пользователя три числа и
создает трехмерный массив соответствующей размерности, заполненный
случайными числами. Выведите массив на экран.

In [31]:
import random as rd

a = int(input("1 Array's len: "))
b = int(input("2 Array's len: "))
c = int(input("3 Array's len: "))

rd_list = [rd.uniform(0, 10) for i in range (a * b * c)]
rd_list
arr = np.array(rd_list)
arr = arr.reshape(a, b, c)
arr

1 Array's len:  4
2 Array's len:  8
3 Array's len:  2


array([[[8.66899706, 1.0274856 ],
        [8.53115498, 9.4426877 ],
        [2.275482  , 8.28744274],
        [0.07597988, 9.80195994],
        [8.861585  , 3.25631276],
        [0.92783106, 3.76321908],
        [1.63010013, 6.73861893],
        [3.35584757, 8.68891728]],

       [[6.56340976, 6.77325823],
        [7.4869231 , 4.54931467],
        [9.2981496 , 1.30383278],
        [5.16199071, 9.73937729],
        [8.90554493, 8.82279936],
        [6.06703903, 0.66500813],
        [3.35982755, 4.26784986],
        [2.29135098, 5.76512021]],

       [[3.7597472 , 2.24312633],
        [0.96593732, 8.34665067],
        [5.41228985, 7.72772021],
        [5.12435735, 0.68315228],
        [1.33832029, 5.68985275],
        [3.69417887, 6.74989272],
        [3.11982441, 8.59387867],
        [6.78856643, 1.32525203]],

       [[9.22756675, 1.58802352],
        [2.15458251, 1.65565717],
        [9.48528053, 2.72510537],
        [7.72798344, 5.96652934],
        [2.53995698, 1.45926956],
        