In [ ]:
Задайте массив grades из оценок студентов 
(оценки от 0 до 100, количество элементов – по количеству студентов в вашей группе). 
Напишите программу, которая увеличит все оценки на 10%.

In [15]:
import numpy as np
np.random.seed(42)

grades = np.random.randint(0, 101, 23)
grades = grades * 1.1
min_grades = np.minimum(grades, 100)

min_grades

array([ 56.1, 100. ,  15.4,  78.1,  66. ,  22. ,  90.2,  94.6,  81.4,
        81.4,  95.7, 100. ,  25.3,   2.2,  23.1,  57.2,   1.1,  95.7,
        31.9,  40.7,   1.1,  69.3,  64.9])

In [17]:
big_grades = grades > 100
grades[big_grades] = 100
grades

array([ 56.1, 100. ,  15.4,  78.1,  66. ,  22. ,  90.2,  94.6,  81.4,
        81.4,  95.7, 100. ,  25.3,   2.2,  23.1,  57.2,   1.1,  95.7,
        31.9,  40.7,   1.1,  69.3,  64.9])

In [21]:
np.minimum(np.random.randint(0, 100, 23) * 1.1, 100).astype(int)

array([ 38,  53,   3,   1,   5,  58,   3,  58, 100,  68,  18,  97,  47,
        36,  80,  67, 100,  14, 100,  51,  15,  78,  84])

In [19]:
grades = np.random.randint(0, 100, 23) * 1.1
grades[grades > 100] = 100
grades

array([  6.6,  22. ,  79.2,  41.8,  18.7,   3.3,  96.8,  64.9,  14.3,
         8.8,  97.9,  57.2,   1.1,  91.3, 100. ,  64.9,  77. ,  47.3,
         7.7,  50.6,  37.4,  84.7,  88. ])

In [20]:
grades.astype(int)

array([  6,  22,  79,  41,  18,   3,  96,  64,  14,   8,  97,  57,   1,
        91, 100,  64,  77,  47,   7,  50,  37,  84,  88])

In [ ]:
Задайте массив prices из цен на товары (цены от 1 до 100 евро, количество – не менее 10). 
Сгенерируйте массив из булевых значений: False – для цен меньше 40 евро, True – для всех остальных. 
С его помощью сделайте скидку 5% для товаров с ценой не ниже 40.

In [24]:
prices = np.random.rand(1, 100, 10)

discount_arr = prices >= 40
discountes_prices = np.where(discount_arr, prices * 0.95, prices)

print(" скидку 5% для товаров с ценой не ниже 40:", discounted_prices)

 скидку 5% для товаров с ценой не ниже 40: [[[0.11047411 0.35462216 0.28723899 0.29630812 0.23360775 0.04209319
   0.01787393 0.98772239 0.42777313 0.38432665]
  [0.67964728 0.21825389 0.94996118 0.78634501 0.089411   0.41758078
   0.87911831 0.94473202 0.46740151 0.61341139]
  [0.16703395 0.99116863 0.2316717  0.94273177 0.64964665 0.60773679
   0.51268851 0.23066981 0.17652803 0.22048621]
  [0.18643826 0.77958447 0.35012526 0.05784268 0.96910263 0.88378588
   0.92775228 0.99490782 0.17389525 0.39624202]
  [0.75823848 0.69602062 0.15389591 0.81583312 0.22444057 0.22381761
   0.53697442 0.59293993 0.58008621 0.09148684]
  [0.87746086 0.26560004 0.12951492 0.88874808 0.9556515  0.86212762
   0.80951607 0.65524198 0.55085737 0.08698676]
  [0.40845321 0.37268852 0.25975378 0.72342011 0.49587574 0.08104622
   0.2201832  0.68325876 0.07613086 0.85120691]
  [0.49514653 0.48058658 0.59240778 0.82468097 0.34780921 0.67801615
   0.56573196 0.26702827 0.87862999 0.79742602]
  [0.65845183 0.85058

In [28]:
prices = np.random.randint(1, 100, 10).astype(float)
print(prices)
discount_arr = prices >= 40
print(discount_arr)
discounted_prices = prices.copy()
discounted_prices[discount_arr] *= 0.95
discounted_prices[discount_arr]

[96. 10. 60. 42. 40. 97. 77. 42. 47. 37.]
[ True False  True  True  True  True  True  True  True False]


array([91.2 , 57.  , 39.9 , 38.  , 92.15, 73.15, 39.9 , 44.65])

In [ ]:
# Алёны вариант

prices = np.random.randint(1, 101, 10)

discount_arr = prices >= 40
discounted_prices = np.where(discount_arr, prices * 0.95, prices)

print(" скидку 5% для товаров с ценой не ниже 40:", discounted_prices)

In [ ]:
prices = np.random.randint(1, 100, 10).astype(float)
print(prices)
discount_arr = prices >= 40
print(discount_arr)
discounted_prices = prices.copy()
discounted_prices[discount_arr] *= 0.95
discounted_prices

In [ ]:
Пусть у вас есть данные о ежедневной стоимости акций компании в течение недели. 
Найдите изменение цены за каждый день, а также дни с минимальным и максимальным изменением. 
(Подсказка: Не забудьте, что когда вы ищите изменение в ценах, то кол-во значений уменьшается на 1, т.к. 
первое значение не с чем сравнивать.)
Пример вывода:
Изменения цен за день: [ 5  5 -8 -4 17  5]
Лучший день: суббота
Худший день: четверг

In [32]:
days_week = ["пн", "вт", "ср", "чт", "пт", "суб", "вс"]
np.random.seed(42)

prices = np.random.randint(1000, 1300, 7)
print(prices)

diff_prices = np.diff(prices)
print(diff_prices)

print(f'the best day of week: {days_week[np.argmax(diff_prices) + 1]}')
print(f'the worst day of week: {days_week[np.argmin(diff_prices) + 1]}')

[1102 1270 1106 1071 1188 1020 1102]
[ 168 -164  -35  117 -168   82]
the best day of week: вт
the worst day of week: суб


In [33]:
#1 variant
days_week = ["пн", "вт", "ср", "чт", "пт", "суб", "вс"]

print(f'the best day of week : {days_week[np.argmax(np.diff(np.random.randint(1000, 1300, 7))) + 1]} \nthe worst day week : {days_week[np.argmin(diff_prices) + 1]}')

the best day of week : вт 
the worst day week : суб


In [ ]:
#2 variant
days_week = ["пн", "вт", "ср", "чт", "пт", "суб", "вс"]

prices = np.random.randint(1000, 1300, 7)
print(prices)

diff_prices = np.diff(prices)
print(diff_prices)

print(f'the best day of week : {days_week[np.argmax(diff_prices) + 1]}')
print(f'the worst day week : {days_week[np.argmin(diff_prices) + 1]}')

In [ ]:
Пять спортсменов участвовали в соревновании, в котором нужно было бежать 2 часа, плыть 1 час и ехать на велосипеде 5 часов.
Первый спортсмен бежал со скоростью 15 км/ч, плыл со скоростью 4 км/ч и ехал на велосипеде со скоростью 25 км/ч.
Соответствующие скорости второго спортсмена: 14 км/ч, 5 км/ч, 27 км/ч.
Третий спортсмен: 16 км/ч, 5 км/ч, 23 км/ч.
Четвертый: 13 км/ч, 5.5 км/ч, 26 км/ч.
Пятый: 12 км/ч, 4.5 км/ч, 30 км/ч.
Побеждает тот, кто преодолел большее расстояние. Напишите программу, которая определяет победителя.
(Подсказка: Подумайте, что здесь можно записать матрицей, что вектором, какая матричная операция определяет пройденное расстояние.)

In [34]:
speeds = np.array([[15, 4, 25], 
                   [14, 5, 27],
                   [16, 5, 23],
                   [13, 5.5, 26],
                   [12, 4.5, 30]])
time = np.array([[2], [1], [5]])
print(speeds @ time)
distance = speeds @ time
np.argmax(distance) + 1

[[159. ]
 [168. ]
 [152. ]
 [161.5]
 [178.5]]


np.int64(5)

In [ ]:
Сделайте срез матрицы из предыдущей задачи, чтобы получить квадратную матрицу (т.е. оставляем только трех спортсменов). 
Сгенерируйте случайный столбец трех чисел от 100 до 200. Будем считать, что это расстояния, пройденные каждым спортсменом. 
Найдите определитель полученной матрицы и матрицу, обратную к ней. 
Умножьте обратную матрицу на случайный столбец (с помощью матричного умножения). Поясните, что вы нашли с помощью такой операции.

In [38]:
sqw_matrix = speeds[0:3]
print(sqw_matrix)

arr = np.random.randint(100, 103, 3).reshape(3, 1)
print(arr)

det = np.linalg.det(sqw_matrix)
print(det)

if det != 0:
    inv_matrix = np.linalg.inv(sqw_matrix)
else:
    print('Matrix is not det')
print(f'Inverter Matrix: {inv_matrix}')

print(inv_matrix @ arr)

[[15.  4. 25.]
 [14.  5. 27.]
 [16.  5. 23.]]
[[100]
 [101]
 [101]]
-110.00000000000004
Inverter Matrix: [[ 0.18181818 -0.3         0.15454545]
 [-1.          0.5         0.5       ]
 [ 0.09090909  0.1        -0.17272727]]
[[3.49090909]
 [1.        ]
 [1.74545455]]


In [ ]:
s = V * t
V ** (-1) * s = V ** (-1) * t
V ** (-1) * s = E * t
V ** (-1) * s = t
