In [ ]:
1. Напишите программу, которая:
a. Запрашивает у пользователя ввод двух списков – в первом 5
элементов, во втором 4. Списки вводятся в виде чисел, разделенных
пробелами.
b. Объединяет введенные списки в один новый список из 9 элементов.
c. Преобразует полученный список в массив NumPy.
d. Трансформирует одномерный массив в матрицу размера 3х3.
Обозначим эту матрицу Х.
e. Выводит полученную матрицу.


In [7]:
import numpy as np

lst_1 = list(map(int, input('Enter 5 elements with spaces').split()))
lst_2 = list(map(int, input('Enter 4 elements with spaces').split()))
lst_total = lst_1 + lst_2
print(lst_total)
X = np.array(lst_total).reshape(3,3)
print(X)

Enter 5 elements with spaces 1 2 3 4 5
Enter 4 elements with spaces 6 7 8 9


[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
2. Продолжение предыдущей задачи. Далее она:
a. В каждой строке и в каждом столбце находит среднее, максимум,
минимум, сумму, произведение.
b. Для всей матрицы находит среднее, максимум, минимум, сумму,
произведение и след.
c. Выводит транспонированную матрицу для матрицы Х.


In [11]:
print(np.mean(X, axis=1)) # описание, что перебирать (столбцы), X-ось
print(np.mean(X, axis=0)) # строки по вертикали (axis = 0, это как Y-ось)
print(np.sum(X, axis=1))
print(np.sum(X, axis=0))

[2. 5. 8.]
[4. 5. 6.]
[ 6 15 24]
[12 15 18]


In [ ]:
# вариант 2

print(f"X:\n{X}")
print()
print("Operations by ROWs")
print(f"Mean by rows X = {np.mean(X, axis=1)}")
print(f"Max  by rows X = {np.max(X,axis=1)}")
print(f"Min  by rows X = {np.min(X,axis=1)}")
print(f"Sum  by rows X = {np.min(X,axis=1)}")
print()
print("operations by COLUMNs")
print(f"Mean by columns X = {np.mean(X, axis=0)}")
print(f"Max  by columns X = {np.max(X,axis=0)}")
print(f"Min  by columns X = {np.min(X,axis=0)}")
print(f"Sum  by columns X = {np.sum(X,axis=0)}")
print()
print("Operations with Full Table") 
print(f"Mean  X = {np.mean(X)}")
print(f"Max   X = {np.max(X)}")
print(f"Min   X = {np.min(X)}")
print(f"Prod  X = {np.prod(X)}")
print(f"Trace X = {np.trace(X)}")
print()
print(f"X.T :\n {X.T}")

In [12]:
lst_trace = np.trace(X)
print(lst_trace)

15


In [13]:
lst_T = X.T
print(lst_T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
