In [1]:
import numpy as np

In [2]:
 #одномерный массив
one_d_array = np.array([1,2,3])

In [3]:
two_d_array = np.array([[1,2,3], [4,5,6]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
list_2d = [[1,2],[3,4]]
two_d_array = np.array(list_2d)
display(two_d_array)

array([[1, 2],
       [3, 4]])

In [ ]:
Данные, заисанные в строчку - одномерный массив, имеет одно измерение
list = [1,2,3,4]

In [7]:
list_2d = [[1],[2],[3],[4]] # вектор-столбец, имеет 2 измерения
two_d_array = np.array(list_2d)
two_d_array

array([[1],
       [2],
       [3],
       [4]])

In [9]:
col = np.array([10], [20])
col_array = np.array(col)
col_array

TypeError: Field elements must be 2- or 3-tuples, got '20'

In [11]:
ones_array = np.ones((3, 4)) # 3 строки, 4 столбца - размер массива
print(ones_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
zeros_array = np.zeros_like(ones_array)
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a = np.arange(0, 9, 2) # 3 параметра - начало, конец и шаг
print(a)
b = np.arange(0., 8, 2)
print(b)


[0 2 4 6 8]
[0. 2. 4. 6.]


In [14]:
a = np.arange(10) # выводит просто целые числа от 0 до 10
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a = np.linspace(0, 8, 7) # есть отрезок от 0 до 8, нужно поделить его 
#на равные кусочки так, чтобы отмеченных точек было 7 штук. т.е. 5 точек внутри и 2 точки по краям
print(a)


[0.         1.33333333 2.66666667 4.         5.33333333 6.66666667
 8.        ]


In [16]:
a = np.linspace(0, 8, 9)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [17]:
a = np.linspace(0, 8, 3)
print(a)

[0. 4. 8.]


In [20]:
# Создайте и выведите последовательность чисел от 10 до 20 
# с постоянным шагом, длина последовательности – 21. Скажите сначала устно, какой должен быть ответ.
a = np.linspace(10, 20, 21)
print(a)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20. ]
