In [ ]:
УРОК 31. ЭЛЕМЕНТЫ МАТРИЧНОЙ
АЛГЕБРЫ. ОБРАТНЫЕ МАТРИЦЫ И
ОПРЕДЕЛИТЕЛЬ

In [3]:
import numpy as np

# Вектор ежедневных расходов (в евро)
daily_expenses = np.array([10, 20, 15, 10, 30, 50, 50])
# Температура воздуха по месяцам (в градусах Цельсия)
temperature = np.array([1, 2, 6, 11, 16, 19, 21, 21, 16, 11, 6, 2])
# Перевод ежедневных расходов в доллары
print(daily_expenses * 1.1)

# Перевод температуры в Фаренгейты
print(1.8 * temperature + 32)


[11.  22.  16.5 11.  33.  55.  55. ]
[33.8 35.6 42.8 51.8 60.8 66.2 69.8 69.8 60.8 51.8 42.8 35.6]


In [4]:
# Доходы мужа по месяцам (в евро)
income_m = np.array([2000, 3000, 3500, 3000, 3000, 2500, 3500, 2000, 2500,
3000, 3500, 4000])
# Доходы жены по месяцам (в евро)
income_f = np.array([1500, 2500, 6000, 1100, 1600, 1900, 2100, 4200, 6000,
1100, 6000, 2000])
# Курс евро к доллару по месяцам
eur2usd = np.array([1.0779, 1.0716, 1.071, 1.096, 1.0879, 1.0834, 1.1056,
1.0916, 1.0686, 1.0561, 1.0804, 1.0902])
# Семейный доход в евро
income = income_m + income_f
print(income)

# Семейный доход в долларах
income_usd = income * eur2usd
print(income_usd)

[3500 5500 9500 4100 4600 4400 5600 6200 8500 4100 9500 6000]
[ 3772.65  5893.8  10174.5   4493.6   5004.34  4766.96  6191.36  6767.92
  9083.1   4330.01 10263.8   6541.2 ]


In [5]:
print(daily_expenses.sum())
print(temperature.mean())
print(daily_expenses.max())
print(temperature[5:8]) #температура за летние месяцы

185
11.0
50
[19 21 21]


In [6]:
# Доходы членов семьи по месяцам
income_matrix = np.array([[2000, 3000, 3500, 3000, 3000, 2500, 3500, 2000,
2500, 3000, 3500, 4000], [1500, 2500, 6000, 1100, 1600, 1900, 2100, 4200, 6000,
1100, 6000, 2000]])
print(income_matrix)

[[2000 3000 3500 3000 3000 2500 3500 2000 2500 3000 3500 4000]
 [1500 2500 6000 1100 1600 1900 2100 4200 6000 1100 6000 2000]]


In [ ]:
Кондитерская производит несколько видов десертов.
Для каждого необходимы мука, яйца и сахар, но в разном количестве.
Необходимое количество описать матрицей, в которой каждая строка описывает одну партию какого-то десерта,
при этом первый столбец показывает количество муки в килограммах, второй столбец – количество яиц в штуках,
третий – количество сахара в килограммах.

In [7]:
# Расход продуктов
goods = np.array([[0.5, 6, 0.1],
[1, 10, 0.5],
[0.3, 10, 0.6],
[0.5, 7, 0.3]])
print(goods)

[[ 0.5  6.   0.1]
 [ 1.  10.   0.5]
 [ 0.3 10.   0.6]
 [ 0.5  7.   0.3]]


In [ ]:
Пусть у нас также известна стоимость килограмма муки, одного яйца и килограмма
сахара. 

In [8]:
prices = np.array([0.75, 0.22, 0.88])
print(goods * prices) # нашли общую стоимость кажого ингредиента

[[0.375 1.32  0.088]
 [0.75  2.2   0.44 ]
 [0.225 2.2   0.528]
 [0.375 1.54  0.264]]


In [9]:
prices_col = prices.reshape(3,1) #преобразуем строку в колонку, потому что 
#таково правило матричного умножения(строки умножаем на столбцы). Numpy позволит умножит строку на строку, 
#но так будет не очень хорошо работать
expenses = goods @ prices_col
print(expenses)
print(expenses.sum()) # нашли общую стоимость каждого блюда

[[1.783]
 [3.39 ]
 [2.953]
 [2.179]]
10.305000000000001


In [ ]:
Фирма закупает ноутбуки и стационарные компьютеры для оборудования офисов на
двух этажах здания. На первом этаже планируется поставить 20 стационарных
компьютеров и 20 ноутбуков. На втором этаже – 12 стационарных компьютеров и 35
ноутбуков. Компьютер стоит 850 евро, ноутбук – 1125 евро. Запишите матрицу А,
описывающую количество компьютеров и ноутбуков на каждом этаже. Запишите
вектор-столбец с ценами компьютеров и ноутбуков. С помощью матричных
операций вычислите стоимость оборудования на каждом этаже.


In [11]:
# Количество оборудования
equipment = np.array([[20, 20], [12, 35]])
# Цены
prices = np.array([850, 1125]).reshape(2,1)
# prices = np.array([[850], [1125]]) # так тоже получится столбец, тоже правильная запись
print(equipment @ prices)

[[39500]
 [49575]]


In [ ]:
Фирма закупает ноутбуки и стационарные компьютеры для оборудования офисов на двух этажах здания.
● На первом этаже планируется поставить 20 стационарных компьютеров и 20 ноутбуков.
● На втором этаже – 12 стационарных компьютеров и 35 ноутбуков.
Стоимость оборудования первого этажа должна составить 40000 евро, а второго этажа – 50000.
Обозначим через Х - стоимость одного ПК, у - стоимость одного ноутбука.

In [ ]:
C: C @ A = E -- определение C = A ** (-1)

A @ X = B -- задача найти X
=====
C @ A @ X = C @ B
E @ X = C @ B
X = C @ B

In [12]:
equipment = np.array([[20, 20], [12, 35]])
inverse = np.linalg.inv(equipment) # обратная матрица
print(inverse)
print(inverse @ equipment)
print(equipment @ inverse)


[[ 0.07608696 -0.04347826]
 [-0.02608696  0.04347826]]
[[ 1.00000000e+00  1.38777878e-16]
 [-1.11022302e-16  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  1.00000000e+00]]


In [13]:
equipment = np.array([[20, 20], [12, 35]])

inverse = np.linalg.inv(equipment) # обратная матрица

# print(inverse) # A ** (-1)
print(inverse @ equipment)
print(equipment @ inverse) 
# A @ (A ** (-1)) = E то и  
# (A ** (-1)) @ A  = E

[[ 1.00000000e+00  1.38777878e-16]
 [-1.11022302e-16  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  1.00000000e+00]]


In [15]:
equipment = np.array([[20, 20], [12, 35]])
expenses = np.array([[40000], [50000]])
inverse = np.linalg.inv(equipment)
x = inverse @ expenses #нашли цены
print(x)


[[ 869.56521739]
 [1130.43478261]]


In [16]:
equipment @ x # проверка: при данных ценах будет стоимость

array([[40000.],
       [50000.]])

In [ ]:
Давайте в предыдущей задаче изменим количество оборудования на этажах: пусть
теперь на втором этаже компьютеров и ноутбуков будет по 30.
Если мы попробуем найти обратную матрицу в этом случае, то получим ошибку:

In [17]:
equipment = np.array([[20, 20], [30, 30]])
inverse = np.linalg.inv(equipment)
print(inverse)


LinAlgError: Singular matrix

In [18]:
equipment = np.array([[20, 20], [30, 30]]) 
det = np.linalg.det(equipment) #проверяем, есть ли опеределитель (determinant), т.е. обратная матрица
print(det) # 0 -значит нет определителя, такая матрица называется выраженной или сингулярной

0.0


In [19]:
equipment = np.array([[20, 20], [12, 35]]) 
det = np.linalg.det(equipment) #проверяем, есть ли опеределитель (determinant), т.е. обратная матрица
print(det) 

459.9999999999997


In [ ]:
Определитель вычисляется только для квадратных матриц.
Обратная матрица тоже есть только у квадратных матриц.

In [ ]:
Матрица goods, как в примере выше, описывает количество муки, яиц и сахара в
трех видах десертов некоторой кондитерской. Известно, что затраты на выпечку
первого десерта составляют 2 евро, второго – 4 евро, третьего – 3 евро. Найдите,
сколько должны стоить мука, яйца и сахар для такой себестоимости десертов.
Для решения задачи составить систему уравнений, найти определитель этой
системы. Если определитель не равен нулю, найти обратную матрицу и значения
переменных.

In [ ]:
# Расход продуктов
goods = np.array([[0.5, 6, 0.1],
[1, 10, 0.5],
[0.3, 10, 0.6]])

In [20]:
expenses = np.array([[2], [4], [3]])
# Расход продуктов
goods = np.array([[0.5, 6, 0.1],
[1, 10, 0.5],
[0.3, 10, 0.6]])
print(np.linalg.det(goods))

-1.4999999999999998


In [21]:
prices = np.linalg.inv(goods) @ expenses
print(prices)

[[1.6 ]
 [0.18]
 [1.2 ]]


In [22]:
goods @ prices #проверка

array([[2.],
       [4.],
       [3.]])