In [ ]:
УРОК 2.1. ИНДЕКСАЦИЯ, НАЧАЛО РАБОТЫ С МАТРИЦАМИ

In [ ]:
Трёхмерный массив (3D-массив) можно представить как набор двумерных таблиц (матриц), сложенных в "стопку". 
В NumPy они имеют три измерения (оси):

Ось 0 (блоки) → Количество столбцов в каждой строке.
Ось 1 (строки) → Количество строк в каждой матрице.
Ось 2 (столбцы) → «Глубина» массива (сколько 2D-матриц в стопке).


cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

cube = np.array([
    [   # Первый блок (cube[0])
        [1, 2],   # Первая строка
        [3, 4]    # Вторая строка
    ],
    [   # Второй блок (cube[1])
        [5, 6],   # Первая строка
        [7, 8]    # Вторая строка
    ]
])

print(cube.shape)  # (2, 2, 2)

array[номер_блока, номер_строки, номер_столбца]

print(cube[1, 0, 1])  # 6  (Блок 1 → Первая строка → Второй элемент)
print(cube[0, 1, 0])  # 3  (Блок 0 → Вторая строка → Первый элемент)

print(cube[1, :, 0])  # [5 7] (Берём 1-й элементы всех строк блока 1)
print(cube[:, 1, 1])  # [4 8] (Берём 2-е элементы 2-й строки во всех блоках)

In [3]:
import numpy as np

In [6]:
b = np.array([6, 4, 10]) 
print(np.sort(b)) # всегда создает новый отсортированный массив, а старый не меняется

[ 4  6 10]


In [9]:
b = np.array([6, 4, 10]) 
b.sort() # сортирует массив на месте, от меньшего к большему, не создает новый, меняет старый
print(b)

[ 4  6 10]


In [11]:
a = np.array([1, 3, 2, 4, 6, 5])
a = np.delete(a, 5) #удаляет по индексу, а не по значению
print(a)

[1 3 2 4 6]


In [12]:
a = np.insert(a, 2, [0, 0]) # вставляет по индексу
print(a)


[1 3 0 0 2 4 6]


In [13]:
a = np.append(a, [1, 2, 3]) # то же самое, что insert, но добавляет в конец
print(a)

[1 3 0 0 2 4 6 1 2 3]


In [14]:
one_d_array = np.array([1, 2, 3])
print(one_d_array[0]) # 1


1


In [15]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d_array[1]) # Выведет вторую строку [4 5 6]

[4 5 6]


In [16]:
print(two_d_array[1, 2]) # Выведет 6, элемент во второй строке и третьем столбце
print(two_d_array[1][2]) # Тоже выведет 6, но обычно принято обращаться через запятую в рамках одних скобок, то же самое, 
#что и print(two_d_array[1, 2])

6
6


In [17]:
int_array = np.array([1, 2, 3])
int_array[2] = 5
print(int_array)

[1 2 5]


In [19]:
# one_d_array = np.array([1, 2, 3])
# two_d_array = np.array([[1, 2, 3], [4, 5, 6]])

print(one_d_array[0:2]) # Выведет [1 2]
print(two_d_array[0:2]) # [[1 2 3], [4 5 6]] – выведет с 0 по 2 строку не вкл
print(two_d_array[0:2, 0:2]) # [[1 2], [4 5]] – выведет с 0 по 2 строку не вкл и с 0 по 2 столбец не вкл

[1 2]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [20]:
print(two_d_array[0, :]) # [1 2 3] – первая строка
print(two_d_array[:, 1]) # [2 5] – второй столбец


[1 2 3]
[2 5]


In [22]:
x = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
s = x[1:3:1]
print(s)

s[0] = 101
print(s)
print(x)
# срез никогда не создает новые массивы, срез - это как view в sql

[2.2 3.3]
[101.    3.3]
[  1.1 101.    3.3   4.4   5.5]


In [23]:
y = x.copy()
y

array([  1.1, 101. ,   3.3,   4.4,   5.5])

In [24]:
x = [1.1, 2.2, 3.3, 4.4, 5.5] #срез создает новый список в отличие от массива
s = x[1:3:1]
print(s)

[2.2, 3.3]


In [25]:
s[0] = 101
print(s)
print(x)

[101, 3.3]
[1.1, 2.2, 3.3, 4.4, 5.5]


In [26]:
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube[1, 0, 1])
print(cube[:, 1, 0])
print(cube[:, 1])

6
[3 7]
[[3 4]
 [7 8]]


In [27]:
b = np.linspace(0, 3, 4)
print(b)
print(b.shape) # меняет на месте, лучше использовать на больших объемах данных

b.shape = 2, 2
print(b)


[0. 1. 2. 3.]
(4,)
[[0. 1.]
 [2. 3.]]


In [32]:
c = b.reshape(2, 2) # создает новый, можно использовать на маленьких объемах данных
print(b)

[[0. 1.]
 [2. 3.]]


In [28]:
print(np.linspace(0, 3, 4).reshape((2, 2)))

[[0. 1.]
 [2. 3.]]


In [33]:
b.ravel() # растягивает многомерные массивы в одну строку, может поменять изначальный, что не всегда удается
print(b)

[[0. 1.]
 [2. 3.]]


In [30]:
print(b.flatten()) # растягивает многомерные массивы в одну строку, всегда возвращает копию, 
#лучше использовать его, если нет проблем с памятью и производительностью

[0. 1. 2. 3.]


In [34]:
print(b.ravel())

[0. 1. 2. 3.]


In [36]:
print(b)
print(b.T) # транспонирует матрицу, только двумерную!
print(b.T.T)
print(b)

[[0. 1.]
 [2. 3.]]
[[0. 2.]
 [1. 3.]]
[[0. 1.]
 [2. 3.]]
[[0. 1.]
 [2. 3.]]


In [37]:
a = np.array([1, 2, 3])
b = np.array([[11], [12], [13]])
print(a * b) # такое умножение работает только на двумерных матрицах


[[11 22 33]
 [12 24 36]
 [13 26 39]]


In [38]:
a = np.array([1, 2, 3])
b = np.array([[11], [12], [13]])
print(a @ b) #сколько столбцов во второй матрице - столько столбцов в итоге. Сколько строк в первой матрице, столько строк в итоге


[74]


In [ ]:
Матричное умножение - вектор-строка х вектор-столбец

In [ ]:
a -- n строк k столбцов
b -- k строк m столбцов

a @ b -- n строк m столбцов

In [40]:
# Вычисляем элемент (0,0):
# Берём первую строку a и первый столбец b:
# (1 * 11) + (2 * 12) + (3 * 13) = 11 + 24 + 39 = 74

# Вычисляем элемент (0,1):
# Берём первую строку a и второй столбец b:
# (1 * 100) + (2 * 200) + (3 * 300) = 100 + 400 + 900 = 1400

# Вычисляем элемент (1,0):
# Берём вторую строку a и первый столбец b:
# (4 * 11) + (0 * 12) + (5 * 13) = 44 + 0 + 65 = 109

# Вычисляем элемент (1,1):
# Берём вторую строку a и второй столбец b:
# (4 * 100) + (0 * 200) + (5 * 300) = 400 + 0 + 1500 = 1900

mat_1 = np.array([[1, 2, 3], [4, 0, 5]])
mat_2 = np.array([[11, 100], [12, 200], [13, 300]])
mat_1 @ mat_2

array([[  74, 1400],
       [ 109, 1900]])

In [ ]:
# Правило:
# Если у нас матрицы (M × K) @ (K × N) → (M × N),
# то число столбцов первой матрицы должно быть равно числу строк второй.

# У нас:

# b имеет (3×2)
# a имеет (2×3)
# Число столбцов b (2) равно числу строк a (2), значит, умножение возможно.

# При умножении:

# Берём строку из b
# Берём столбец из a
# Перемножаем соответствующие элементы и складываем их

# Вычисляем элемент (0,0)
# Берём первую строку b и первый столбец a:
# (11 * 1) + (100 * 4) = 11 + 400 = 411

# Вычисляем элемент (0,1)
# Берём первую строку b и второй столбец a:
# (11 * 2) + (100 * 0) = 22 + 0 = 22

# Вычисляем элемент (0,2)
# Берём первую строку b и третий столбец a:
# (11 * 3) + (100 * 5) = 33 + 500 = 533

# Вычисляем элемент (1,0)
# Берём вторую строку b и первый столбец a:
# (12 * 1) + (200 * 4) = 12 + 800 = 812

# Вычисляем элемент (1,1)
# Берём вторую строку b и второй столбец a:
# (12 * 2) + (200 * 0) = 24 + 0 = 24

# Вычисляем элемент (1,2)
# Берём вторую строку b и третий столбец a:
# (12 * 3) + (200 * 5) = 36 + 1000 = 1036

# Вычисляем элемент (2,0)
# Берём третью строку b и первый столбец a:
# (13 * 1) + (300 * 4) = 13 + 1200 = 1213

# Вычисляем элемент (2,1)
# Берём третью строку b и второй столбец a:
# (13 * 2) + (300 * 0) = 26 + 0 = 26

# Вычисляем элемент (2,2)
# Берём третью строку b и третий столбец a:
# (13 * 3) + (300 * 5) = 39 + 1500 = 1539

a = np.array([[1, 2, 3], [4, 0, 5]])
b = np.array([[11, 100], [12, 200], [13, 300]])
print(b @ a)


In [41]:
mat_1 = np.array([[0, 1], [0, 1]])
mat_2 = np.array([[-1, 0], [2, 3]])
print(mat_1 @ mat_2)
print(mat_2 @ mat_1)

[[2 3]
 [2 3]]
[[ 0 -1]
 [ 0  5]]


In [44]:
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
print(cube[:, 0])


[[1 2]
 [5 6]]


In [46]:
print(cube[1, :, 0])


[5 7]


In [47]:
s = cube[:, 1]
s *= 10
print(s)
print(cube)

[[30 40]
 [70 80]]
[[[ 1  2]
  [30 40]]

 [[ 5  6]
  [70 80]]]


In [48]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a @ b

array([[19, 22],
       [43, 50]])

In [49]:
I = np.eye(4) #единичная матрица
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [50]:
a = np.arange(16).reshape(4,4)
print(a)
print(a @ I) # умножение на единичную матрицу будет как на единицу

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [51]:
a = np.arange(16).reshape(4,4)
print(a)
print(I @ a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [57]:
def f(i, j, k):
    print(i)
    print(j)
    return 10 * (i + 1) + (j + 1) + k ** 2
    
print(np.fromfunction(f, (3, 4, 2), dtype=np.int64))

[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]]
[[[0 0]
  [1 1]
  [2 2]
  [3 3]]

 [[0 0]
  [1 1]
  [2 2]
  [3 3]]

 [[0 0]
  [1 1]
  [2 2]
  [3 3]]]
[[[11 12]
  [12 13]
  [13 14]
  [14 15]]

 [[21 22]
  [22 23]
  [23 24]
  [24 25]]

 [[31 32]
  [32 33]
  [33 34]
  [34 35]]]


In [58]:
def f(i, j):
    print(i)
    print(j)
    return 10 * i + j
    
print(np.fromfunction(f, (3, 4), dtype=np.int64))

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]


In [59]:
a = np.array([1, 3, 2])
b = np.array([4, 5, 6])
a = np.hstack((a, b)) #склеивает горизонтально,лучше использовать для двумерных. А для многомерных лучше concatenate(универсальней)
print(a)


[1 3 2 4 5 6]


In [60]:
a = np.array([1, 3, 2])
b = np.array([4, 5, 6])
a = np.vstack((a, b)) # склеивает вертикально
print(a)

[[1 3 2]
 [4 5 6]]


In [62]:
print(np.hsplit(a, [3, 5])) # вырезает кусок по индексам

[array([[1, 3, 2],
       [4, 5, 6]]), array([], shape=(2, 0), dtype=int64), array([], shape=(2, 0), dtype=int64)]


In [63]:
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[4, 5], [6, 7], [8, 9]])
print(a)
print(b)
print(c)


[[0 1]
 [2 3]]
[[4 5 6]
 [7 8 9]]
[[4 5]
 [6 7]
 [8 9]]


In [64]:
print(np.hstack((a, b))) # лучше использовать hstack вместо concatenate


[[0 1 4 5 6]
 [2 3 7 8 9]]


In [65]:
print(np.vstack((a, c)))


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [66]:
print(b)
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))


[[4 5 6]
 [7 8 9]]
39
[11 13 15]
[15 24]


In [67]:
print(b.max())
print(b.max(axis=0)) # в каждом столбце
print(b.min(axis=1)) # в каждой строке

9
[7 8 9]
[4 7]


In [68]:
print(np.trace(b)) # след матрицы – сумма диагональных элементов

12


In [69]:
X = np.arange(24).reshape(2, 3, 4) # Многомерный массив называется тензором
print(X)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [70]:
print(X.sum(axis=0)) # ось 0 - это столбцы


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [71]:
print(X.sum(axis=(1, 2)))  # Суммируем сразу по двум осям


[ 66 210]


In [72]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print(a * b) #BROADCASTING


[2 4 6]


In [73]:
a = np.array([[ 0, 0, 0],
[10, 10, 10],
[20, 20, 20],
[30, 30, 30]])
b = np.array([0, 1, 2])
print(a + b)


[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [2]:
# Подумайте, массив какого размера получится, если перемножить массив 4х1х3 и
# массив 12х1. Убедитесь на практике в правильности вашего ответа.
import numpy as np
a = np.ones((4, 1, 3)) # 4 1 3
b = np.ones((12, 1))# 1 12 1. Python добавляет единицу сначала справа, потом слева для того, чтобы растянуть
mul_shape = (a * b).shape
print(mul_shape)


(4, 12, 3)


In [81]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = a[np.newaxis, :] # добавление оси axis0
print(b.shape)

(1, 10)


In [82]:
c = a[np.newaxis, :, np.newaxis]
print(c.shape)

(1, 10, 1)


In [83]:
a = np.array([[0, 0, 0],
[10, 10, 10],
[20, 20, 20],
[30, 30, 30]])
b = np.array([0, 1, 2])
result = a / (b + 1) # делим поэлементно
print(result)


[[ 0.          0.          0.        ]
 [10.          5.          3.33333333]
 [20.         10.          6.66666667]
 [30.         15.         10.        ]]


In [90]:
# Создайте два массива: первый - двумерный массив (матрица) размером 6x4, 
# заполненный числами от 10 до 33; второй - одномерный массив длины 4 с числами от 15 до 18. 
# Выполните поэлементное деление матрицы на одномерный массив, 
# используя правила Broadcasting, и вычислите след результирующей матрицы.

import numpy as np

f1 = np.arange(10, 34, 1).reshape(6, 4)
f2 = np.arange(15, 19, 1)
print(f1)
print(f2)

div_f = f1 / f2
print(div_f)

trace_f = np.trace(div_f)
print(trace_f)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]
[15 16 17 18]
[[0.66666667 0.6875     0.70588235 0.72222222]
 [0.93333333 0.9375     0.94117647 0.94444444]
 [1.2        1.1875     1.17647059 1.16666667]
 [1.46666667 1.4375     1.41176471 1.38888889]
 [1.73333333 1.6875     1.64705882 1.61111111]
 [2.         1.9375     1.88235294 1.83333333]]
4.169526143790849


In [93]:
# Создайте двумерный массив размером 3x8, заполненный числами от 1 до 24. Выполните суммирование по первой оси (axis=0), 
# посчитайте среднее значение по второй оси. Выведите полученный результат.

s1 = np.arange(1, 25, 1).reshape(3, 8)
print(s1)
np.sum(s1, axis=0)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


array([27, 30, 33, 36, 39, 42, 45, 48])

In [94]:
np.mean(s1, axis=1) # когда ось 1, то строки оставляем неподвижными, в рамках одной строки считаем

array([ 4.5, 12.5, 20.5])

In [74]:
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [75]:
print(cube[1, 0, 1])


6


In [76]:
print(cube[:, 1, 0])


[3 7]


In [77]:
print(cube[:, 1])

[[3 4]
 [7 8]]


In [79]:
aa = np.array([[0, 1], [0, 1]])
bb = np.array([[-1, 0], [2, 3]])
aa @ bb

# 0 * (-1) + 1 * 2 =2
# 0 * 0 + 1 * 3 = 3
# 0 * (-1) + 1 * 2 = 2
# 0 * 0 + 1 * 3 = 3


# 1 * 0 + 1 * 3 = 3
#  [[2, 3], [2, 3]]

array([[2, 3],
       [2, 3]])

In [80]:
aa = np.array([[0, 1], [0, 1]])
bb = np.array([[-1, 0], [2, 3]])
bb @ aa

# -1 * 0 + 0 * 0 = 0
# -1 * 1 + 0 * 1 = -1
# 2 * 0 + 3 * 0 =0
# 2 * 1 + 3 * 1 =5
# [0, -1], [0, 5]

array([[ 0, -1],
       [ 0,  5]])